### ISSUE TITLE
Some Icons are invisible and the updates after edits are not working

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#160] opened 2023-01-04 11:36 UTC
When I edit the Config Automation to add some entities or delete something the updates are not shown in the NS Panel.
Sometime later, sometimes never. Some Icons are there and functional but they are invisible. 
I played a bit with the  delay slider for network sync but with no success.

Any hints?

**Comment by deejaybeam** [comment] 2023-01-04 12:52
You Just have to reboot the nspanel itself. While initializing all available entities are Set. This hast nothing to do with the sync/delay, this is only for the live StateUpdate of the entities.

**Comment by MarkuZP** [comment] 2023-01-04 14:33
No, you get me wrong! I meant that after a reboot the updates are not shown sometimes! Some Icons are invisible but there.

**Comment by deejaybeam** [comment] 2023-01-04 15:04
What do you reboot? HA, or the NSPanel itself?
If you reboot the NSPanel and you have missing entities, that means, that some of the entities are not reachable while getting current state, which is required to set it on the display. If the current state of an entitiy is "unavailable" or "unknown" than it is ignored, because it is not possible to set a state on the display.
What you can try, is to create a helper with the exact entity "input_boolean.trigger_nspanel_boot" this is an internal helper while testing. When you turn this on, then the init-code of the display is executed - you can try this, or assign it to a button on the display itself.

**Comment by Blackymas** [comment] 2023-01-05 18:55
I think the problem is your network - pls try this setting

![Bildschirmfoto 2023-01-05 um 19 51 37](https://user-images.githubusercontent.com/41958506/210858096-7b947c53-10f8-416c-beb0-814e1050f148.png)

If e.g. the network is not optimal or too much load in the WLAN, this can lead to things missing or not working.

Therefore, we have built in the blueprint this value so that everyone can adapt it to his network.

I had at the very beginning with 0 ms delay the same problem although I have a business WLAN for a lot of money :)

**Comment by MarkuZP** [comment] 2023-01-05 21:39
Its much better now after rebuilding my config Automation from scratch. Maybe it was damaged!

**Closed** 2023-01-05 21:54 UTC
Labels: question
