### ISSUE TITLE
Error compiling/uploading.

### ISSUE THREAD

**Issue by VanFlipsen** [Blackymas/NSPanel_HA_Blueprint#1465] opened 2023-12-23 05:24 UTC
Error compiling when you change your wifi password.

I try to get my NSPanel to a new WiFi ssid and password, i get an error while compiling.

ERROR Error auth result: Error: Authentication invalid. Is the password correct?

Is there a way to override the password.

**Comment by edwardtfn** [comment] 2023-12-23 08:00
There are.

Basically, this happens as in the early earas of this project we decided to use Wi-Fi password as OTA password. It works fine, adds some security to the system, preventing someone with access to your network to take control of your device, but it breaks when you decide to change your Wi-Fi password.
So, the problem is only with OTA. If you flash via serial it will work fine, until you change your password again, when serial will be need again. If you don't remember your old password, this is the only way. And this also shows how that added security is limited to people without physical access to your panel. 😞 

However, if you still know your old Wi-Fi password, you can still do it via OTA. Just add this to your yaml:
```yaml
ota:
  password: <<your_old_wifi_password>>
```
You probably don't want keep that old password in your yaml forever, so you can add this to set a different one (your new Wi-Fi password or anything else - or use a `""` to completely remove OTA password):
```yaml
# change OTA password, remove after flashing
esphome:
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("New password");
ota:
  password: !secret wifi_password
  id: my_ota
```
This process is better described [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#custom-ota-password) and [here](https://esphome.io/components/ota.html#updating-the-password).

Please try that and let me know if you get any issue.

**Comment by VanFlipsen** [comment] 2023-12-25 09:42
Thank you for the clear explanation. 
 
I thought I couldn't use the password twice in the yaml. Apparently that works.

I'm happy with the solution for now.

**Comment by edwardtfn** [comment] 2023-12-25 10:16
The settings on your local yaml will be merged with the settings from the remote package. When you have a conflict, in some cases your local settings will be used, in some cases you have to use an `!extend` to add into the one from remote packages. In most of the cases it works just fine.
We have a lot of different cases using this in that first link I've shared.

**Closed by edwardtfn** 2023-12-25 10:16 UTC
Labels: Question
