### ISSUE TITLE
`QUESTION` Code won't compile.  nspanel_esphome.yaml is not a valid YAML file

### ISSUE THREAD

**Issue by szpemes** [Blackymas/NSPanel_HA_Blueprint#1632] opened 2024-01-14 12:19 UTC
### Question

Can't find solution compiling code on ESPHome.

### Additional Details

Message when I try to validate before download:
Failed config

packages: [source /config/esphome/panel.yaml:12]
  
  nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.

Code copied from Github edited only wifi details.
Couldn't find solution on web, please advise.

**Comment by andythomas** [comment] 2024-01-14 12:55
It is hard to help without the file `panel.yaml`. Could you fill in some made-up password and and only validate again, i.e. click the three dots in the main view of esphome. If it fails again, please post the yaml file. If I had to guess, you have too few/too many `"` somewhere or the indentation is incorrect after you filled in your wifi credentials.

**Comment by szpemes** [comment] 2024-01-14 13:14
Thanks for quick reply, here is the code:
substitutions:
  # Settings - Editable values
  device_name: "nspanel" 
  wifi_ssid: "fakefake"
  wifi_password: "Fake7654"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

**Comment by andythomas** [comment] 2024-01-14 13:38
It looks like the indentations are off. It should be (for example)

```
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
```

and _not_ 

```
packages:
remote_package:
url: https://github.com/Blackymas/NSPanel_HA_Blueprint
```

**Comment by szpemes** [comment] 2024-01-14 13:55
Sorry, paste text didn't seem to work. I attach file,  indentations are OK.
[panel.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13931703/panel.txt)

**Comment by andythomas** [comment] 2024-01-14 14:19
My esphome can successfully validate the file you attached. Just to confirm

1) You cannot compile and the compilation stops with the message: `nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.`
2) You manually validate via the 'three dot' menu in esphome and it stops with the message: `nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.`

Which one is your case?

**Comment by szpemes** [comment] 2024-01-14 14:29
I just tried 4 different modes with the same result: 
Failed config

packages: [source /config/esphome/panel.yaml:16]
  
  nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.
  remote_package:  [source /config/esphome/panel.yaml:17]

Methods:
1 manually validate via the 'three dot' menu in esphome
2. manually install via the 'three dot' menu in esphome _manual download_ modern format
3. manually install via the 'three dot' menu in esphome _manual download_ legacy format
4. manually install via the 'three dot' menu in esphome_plug into this computer- preparation failed

**Comment by andythomas** [comment] 2024-01-14 14:38
Disclaimer: This is a wild guess!

It seems that most weird and hard to diagnose issues arise from an underpowered machine running the compile process. Then, the first thing to try is to, e.g., start the yaml file with

```
esphome:
  compile_process_limit: 1
```

However, in the other cases the complier crashes with a different error message. So, I am out of ideas...A broken esphome installation seems really unlikely.

**Comment by szpemes** [comment] 2024-01-14 15:01
I tried all you said, no luck alas.
There is a constant red cross at the beginning of the line url: https://github.com/Blackymas/NSPanel_HA_Blueprint.
It doesn't like whatever coded behind the link. Red even before validation.

**Comment by andythomas** [comment] 2024-01-14 15:11
Is it possible that the access to the repository is somehow blocked, at least from the HA computer?

**Comment by szpemes** [comment] 2024-01-14 15:45
This HA is running on a PI4, normal home setup, no special setup on the router can see the web.
I have another PI4 on a remote site. I just logged in and created a new ESPHome device. 
Pasted the same code, this one is complaining straight away, message is 
Failed to load packages. nspanel_esphome.yaml does not exist in repository.
Really don't know what is wrong.

**Comment by edwardtfn** [comment] 2024-01-14 23:32
# Compiling Errors Guide
It seems the issue is due to insufficient resources on your server for compiling.
Here are two suggestions:

## Free Up Server Resources
1. Add the following to your device's YAML to reduce resource usage (this may slow down the compilation process):

    ```yaml
    # Limit the amount of resources used for compiling
    esphome:
      compile_process_limit: 1
    ```

    > [!TIP]
    > Place this in a dedicated customization section in your YAML for easier maintenance,
    similar to [this example](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#instructions).

2. Restart your host system, not just Home Assistant. Use the advanced options to **Reboot system**, which also restarts add-ons and can free up memory.

3. Temporarily stop non-essential add-ons in Home Assistant, especially resource-intensive ones like Studio Code Server.

4. Clean up build files (on the ESPHome Dashboard, click the 3-dot meny related to your device and then "**Clean Build Files**").

5. Try compiling again.

6. After completion, restart your host system to reactivate the stopped add-ons.

## Compile Using Your Computer
1. Install ESPHome on your computer (Windows, Mac, or Linux) following this guide: [Installing ESPHome Manually](https://esphome.io/guides/installing_esphome.html).

2. With ESPHome installed locally, you can use the ESPHome Dashboard or the [ESPHome Command Line Interface](https://esphome.io/guides/cli.html#command-line-interface) for compilation.

**Comment by edwardtfn** [comment] 2024-01-14 23:46
Your original message looks to be related to a simple "Clean build files"

**Comment by edwardtfn** [comment] 2024-01-15 00:30
- #1636

**Comment by edwardtfn** [comment] 2024-01-16 12:57
Hey @szpemes, are you still facing this issue or should we close it?

**Closed** 2024-01-16 20:13 UTC
Labels: Question, Error: Compiling
