### ISSUE TITLE
Slow loading of pages

### ISSUE THREAD

**Issue by EvertonCa** [Blackymas/NSPanel_HA_Blueprint#571] opened 2023-03-30 22:08 UTC
I was using version 3.0 before and I upgraded to version 3.2.1 yesterday. I noticed that now, the pages loading is much slower than before, taking sometimes 7 seconds for the page to show up. Is that expected or is there something I could do to speed this up?

**Comment by blehers** [comment] 2023-03-31 07:22
According to issue [#493](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/493#issuecomment-1478359497) slow page loading seems to be the new normal. A fix in the release 3.2.1 should have brought some improvements. I'm not so happy about it either.

But first, a big thank you to @Blackymas and the dev team pushing this project this far. I really appreciate it!

For me, this project is now at a very crucial decision point on the roadmap:

1. delivering growing, feature-rich functionality
vs.
2. maintaining a light-switch-like (instantaneous) behavior

I myself am clearly on team 2. I use the NSPanel as a versatile (ligth, shutter, etc.) switch with sensor data and so speed and instantaneous responses are key. Customization to some degree is a plus, but I don't need individual icons, colors and all that stuff. Even the home screen with weather forecasts and time could be omitted. If I'd like to have a lot of functionality, I would go for a tablet solution and get multimedia support there. 

@Blackymas Would it be possible for you and your team to deliver a simplified, fast version in parallel?

**Comment by hkr086** [comment] 2023-03-31 07:45
I hope the guys manage to fix this as I also  have a lot of delay on all my ns panels. If you reboot them things get better but still no where near as they were before 
It's a great project and I hope it gets better.

**Comment by EvertonCa** [comment] 2023-04-01 00:07
> According to issue [#493](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/493#issuecomment-1478359497) slow page loading seems to be the new normal. A fix in the release 3.2.1 should have brought some improvements. I'm not so happy about it either.
> 
> But first, a big thank you to @Blackymas and the dev team pushing this project this far. I really appreciate it!
> 
> For me, this project is now at a very crucial decision point on the roadmap:
> 
> 1. delivering growing, feature-rich functionality
>    vs.
> 2. maintaining a light-switch-like (instantaneous) behavior
> 
> I myself am clearly on team 2. I use the NSPanel as a versatile (ligth, shutter, etc.) switch with sensor data and so speed and instantaneous responses are key. Customization to some degree is a plus, but I don't need individual icons, colors and all that stuff. Even the home screen with weather forecasts and time could be omitted. If I'd like to have a lot of functionality, I would go for a tablet solution and get multimedia support there.
> 
> @Blackymas Would it be possible for you and your team to deliver a simplified, fast version in parallel?

Yes, I bought another NSPanel that just arrived and it is basically unusable. It is taking so long to load that the home page timeout activates before it loads.. I think I will rollback to 3.1 and see.. Even for the physical button there is a huge delay...

**Comment by Blackymas** [comment] 2023-04-01 07:03
Hello, yes it has slowed down and yes we are working on it.

We have probably also found something to speed it up.

Can you upload a video?
Because even with the current stable it should not take as long as you write here.

Otherwise you have another problem like

- network problems
- ha host system too slow
- in blueprint delay times to 1 digit
- entity query takes too long

**Comment by hkr086** [comment] 2023-04-01 21:04
Hi , 
this is the delay I have on my panels almost all the same. I have 4 ns panels if it makes a difference. Is there something I can do to improve? Raspberry pi is running constantly 40 to 50 %cpu and also 40 % memory. 
https://we.tl/t-2fiGXTYsw7

**Comment by EvertonCa** [comment] 2023-04-02 00:13
> Hello, yes it has slowed down and yes we are working on it.
> 
> 
> 
> We have probably also found something to speed it up.
> 
> 
> 
> Can you upload a video?
> 
> Because even with the current stable it should not take as long as you write here.
> 
> 
> 
> Otherwise you have another problem like
> 
> 
> 
> - network problems
> 
> - ha host system too slow
> 
> - in blueprint delay times to 1 digit
> 
> - entity query takes too long
> 
> 
> 
> And pressing the buttons no matter if buttonpage or hw button has nothing to do with the change.
> 
> 
> 
> If they go slowly it is because of your system or entity.
> 
> 

Hello!

Here's a video of one of my NSPanels 

https://youtu.be/x2qEVamow0c

I have a 4 core mini pc running HA and full ubiquiti network, with a AP really close to the switches.

The blueprint delay, you recommend trying 2 digits values?

**Comment by blehers** [comment] 2023-04-02 18:59
It takes about the same time on my installation (delay 10 ms, NUC, AP 3 meters away).

https://user-images.githubusercontent.com/51756488/229373193-5bd6209c-d20b-4bb2-80ae-41b9f125f6d3.mov

**Comment by odehrish** [comment] 2023-04-02 20:30
i have the problem like blehers its also slow

**Comment by Blackymas** [comment] 2023-04-02 20:53
thanks for the videos.

Strange that it takes so long. 
It is true we had to rebuild the code and the TFT.

As an explanation.

With version 3.1
the buttons were stored as global variables. For one button we need 6 fields to create this button design.

This button design is unique because it is so complicated.

That means we need 48 global fields per page and 192 global fields for all 4 pages.

The global fields eat a lot of memory because they store the current value - so that we were at the limit and we could not introduce more functions and improvements.


From version 3.2
we have now set all fields to local. That means with 192 fields we save extremely memory.

But this has the disadvantage that we have to refill all fields with every page call and have to query all entities before.

The query can therefore go from host to host differently fast, depending on how fast the HA host is.



Conclusion:
We will probably not get the same speed as v.3.1 in the near future. 

BUT

we have already found a solution to minimize the load time extremely.

But that always depends on how fast your HA host is. We use a RPI 4 or a mini PC. I could not reproduce your long loading time.

**Comment by EvertonCa** [comment] 2023-04-02 22:08
> thanks for the videos.
> 
> 
> 
> Strange that it takes so long. 
> 
> It is true we had to rebuild the code and the TFT.
> 
> 
> 
> As an explanation.
> 
> 
> 
> With version 3.1
> 
> the buttons were stored as global variables. For one button we need 6 fields to create this button design.
> 
> 
> 
> This button design is unique because it is so complicated.
> 
> 
> 
> That means we need 48 global fields per page and 192 global fields for all 4 pages.
> 
> 
> 
> The global fields eat a lot of memory because they store the current value - so that we were at the limit and we could not introduce more functions and improvements.
> 
> 
> 
> 
> 
> From version 3.2
> 
> we have now set all fields to local. That means with 192 fields we save extremely memory.
> 
> 
> 
> But this has the disadvantage that we have to refill all fields with every page call and have to query all entities before.
> 
> 
> 
> The query can therefore go from host to host differently fast, depending on how fast the HA host is.
> 
> 
> 
> 
> 
> 
> 
> Conclusion:
> 
> We will probably not get the same speed as v.3.1 in the near future. 
> 
> 
> 
> BUT
> 
> 
> 
> we have already found a solution to minimize the load time extremely.
> 
> 
> 
> But that always depends on how fast your HA host is. We use a RPI 4 or a mini PC. I could not reproduce your long loading time.
> 
> 
> 
> 
> 
> one more hint: 
> 
> 
> 
> You can set the delay in the Blueprint to 0 or to 1 if you have a reasonable WiFi.
> 
> 
> 
> The delay we have only installed for people who have strong problems with the Wifi.
> 
> 
> 
> If you have a reasonable WiFi set it to 0 or 1.
> 
> 
> 
> 
> 
> Version v.3.2.2 with the improved loading time is already on the way and will come the next days pnline.

Thanks for the explanation.

I tried setting the delay to 15 (it was 1 on my last video) and could not see any change. Now it's 0 delay and this is the video.

You can see the delay for activating the relays (that why I opened the issue about allowing direct control of the relay) and also, the homescreen is taking so long that sometimes it just won't load

https://youtube.com/shorts/s41SvGCXlpg?feature=share

**Comment by EvertonCa** [comment] 2023-04-04 02:46
Both my panels are behaving the same way.

![image](https://user-images.githubusercontent.com/28612672/229673027-55a50ed6-fcd2-46a7-97ea-51419227c51c.jpeg)

I can even control the relays via HA dashboard or a nodeRED automation through other switches and it activates almost instantly, but using the button in the panels is a nightmare. 

Do you think something might be wrong with the HA automation? Because I did nothing different from what is available via the template and now (since I started this issue) none of the 2 panels will load the home screen. I have tried restarting HA, the NUC HA is installed on and the NSPanels and it just keeps stuck in loading the home screen.

**Comment by Blackymas** [comment] 2023-04-04 08:36
v3.2.2 is available please try and report

**Comment by blehers** [comment] 2023-04-04 13:11
Thank you for the update! It's still not as fast as before and a second and a half away the desired light switch feeling, but it has cut the load time in half. I'm keeping my fingers crossed for more improvements.

https://user-images.githubusercontent.com/51756488/229802319-bdd6fa51-a2c5-4897-931d-e715e29a2adc.mov

**Comment by EvertonCa** [comment] 2023-04-04 15:29
It's muuuch faster now. 

https://user-images.githubusercontent.com/28612672/229842094-2cc32b02-3b49-4070-bde2-d211dcc6fc23.MOV

Can this change be enabled to the buttons as well?

**Comment by Blackymas** [comment] 2023-04-04 16:27
What do you mean with Buttons?

**Comment by EvertonCa** [comment] 2023-04-04 16:29
> What do you mean with Buttons?

The physical buttons controlling the relays. Altho I don't know if this changes would apply to how the buttons control the relays

**Comment by Blackymas** [comment] 2023-04-04 21:14
As already described above. This has nothing to do with the relays.

I'm closing the ticket because the real issue was the loading of the page, which we have improved with v.3.2.2.

**Closed by Blackymas** 2023-04-04 21:14 UTC
Labels: question
