### ISSUE TITLE
Entity icon not lit after activation when activating a scene.

### ISSUE THREAD

**Issue by jayjayvm** [Blackymas/NSPanel_HA_Blueprint#691] opened 2023-04-18 20:03 UTC
Title summs it up, I have scenes on one page, but none of them go lit up when activated even though the scene gets triggered.
Posted this in the wrong post I thing but hope to get this solved, thanks.

**Comment by rleongcs** [comment] 2023-04-19 08:58
I am seeing the same behavior. I also have assigned the hardware button to one of the scene in the room and even the blue line will not show.

I would say there is nothing wrong as it is a scene and is in line with HA default UI which does not change any color as well. Let's see what the developer says.

**Comment by edwardtfn** [comment] 2023-04-19 11:58
This is the same topic of #690 

The problem is that in Home Assistant, some domains, like scene, button, automation, script (and I'm probably missing some others) doesn't have a binary state (on/off or true/false) like a switch or a light. So there's no `on` state for those.
We should think about some improvement in the UI so when the user press that button the back color changes like if the button was `on` for an instant and then back to `off`, so users will know the systems responded to the button press.

**Comment by jayjayvm** [comment] 2023-04-19 14:59
If only I could use the number helper I incorperated in the scenes to trigger the toggle state of the nspanel state of the scene, that could work!

**Comment by rleongcs** [comment] 2023-04-19 15:08
Not sure how you are gonna toggle it to off as showing it always on does not make sense. As you can obviously switched some of the lights or switches to other colors or off after you have activated the scene.

I totally agree with what @edwardtfn mentioned about having some kind of feedback to user if they press the button.

**Comment by deejaybeam** [comment] 2023-04-19 18:34
Agree with (nearly) everyting. This was alredy implemented in an older version, but looks like that after all the (awesome) work of @edwardtfn the visual feedback when "activating" a button/scene/input_button is missing now.
Of course, I will add that again - a flash of the button on the display for 1 second to have the feedback again.
A feedback of "is a scene active" is just not possible - we can just display information we got from HA and the same is true for buttons - they are just "pressed" you can´t see if a button was pressed...
Thanks for the feedback!
We are currently do a hard job to change nearly the whole code in the background to make everything faster/more stable/better errorhandling

**Comment by rleongcs** [comment] 2023-04-20 14:37
@deejaybeam I have just recorded a video showing the visual feedback I believed is implemented by @edwardtfn. It is still there. The only time there is no feedback is when you press the physical button which is associated to a scene, then there is no indication by the blue line (Video 1).
One thing you can see from the video is after pressing the scene button and getting the visual feedback, the icon of the button is missing (Video 2). A bug?

https://user-images.githubusercontent.com/61628312/233399064-f99ddb41-3be8-4be0-be22-d972ee162f32.MOV

https://user-images.githubusercontent.com/61628312/233399210-699801db-d4c1-4fd8-9bfc-7b9a65632ebb.MOV

**Comment by deejaybeam** [comment] 2023-04-20 17:50
ok - thanks for your feedback.
It looks like you have installed the latest stable (from main-repo) version
In the current (now beta-version 3.2.3) this functionality was broken.
This is now fixed again in latest dev-version 3.3
But you give a good hint - this should be also implemented for the HW-Buttons.
I will have a look...

**Comment by edwardtfn** [comment] 2023-04-25 19:01
> But you give a good hint - this should be also implemented for the HW-Buttons.

Done! ;)

**Closed** 2023-05-01 19:57 UTC
