### ISSUE TITLE
No more weather forecast

### ISSUE THREAD

**Issue by addibr** [Blackymas/NSPanel_HA_Blueprint#1335] opened 2023-11-24 22:36 UTC
Ever since the V 4.1 update i do not get weather forecasts anymore. It worked flawlessly up until version 4.0.2, but since the last two updates it broke for me. 
The weather on the main pare is shown correctly, but when I tap on it the forecast pages just show the day and date, but no weather information.

**Comment by misery** [comment] 2023-11-24 22:37
Seems a duplicate of #1259.

**Comment by edwardtfn** [comment] 2023-11-24 22:52
Which weather integration are you using?

**Comment by addibr** [comment] 2023-11-24 23:00
> Which weather integration are you using?

I was using OpenWeatherMap, but the switched to AccuWeather to make sure that this is not the reason for the problem. But on AccuWeather the issue presists.

**Comment by addibr** [comment] 2023-11-24 23:04
Ok, i did not enable the weather forecast checkbox when switching to AccuWeather. Enabling it now solved the problem. So it is just an OpenWeatherMap compatibility issue like @misery suggested. AccuWeather works fine.

**Closed** 2023-11-24 23:04 UTC
Labels: bug

**Comment by edwardtfn** [comment] 2023-11-25 02:00
OpenMapWeather should work, but you have to select the right option: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1259#issuecomment-1807290282
