### ISSUE TITLE
`QUESTION` ESPHome can't be initialized

### ISSUE THREAD

**Issue by jimmyhenne** [Blackymas/NSPanel_HA_Blueprint#1614] opened 2024-01-12 17:55 UTC
### Question

How can I restore ESPHome?

### Additional Details

**TFT-Version 4.2
ESPHOME no result
Blueprint 4.2**

Hey there,

I'm rather new to NSPanel and this repo. I bought a NSPanel and succesfully flashed and set up v 4.1.4. Then I bought two more panels and also succesfully flashed them, but with new v 4.2. Then I updated the 'old' panel to 4.2 and it was fine at first. But since power off and power on it can't initialize ESPHome. The boot screen is stuck at ESPHome and prompts #retry 1-9.
I validated and installed the device in ESPHome in HA for 5-6 times manually but I can't manage to get it to work again.

This is my panels yaml
```

substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbuero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://PANEL-IP/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by andythomas** [comment] 2024-01-12 19:00
Could you post a log from one of the panels from ESPHome? Also, could you take a photograph of the boot screen? Is it stuck at ESPHome showing retries or the Blueprint? 

> TFT-Version 4.2
> ESPHOME no result
> Blueprint 4.2

This seems odd, I assumed the info is filled in sequence.

**Comment by jimmyhenne** [comment] 2024-01-12 20:42
all devices are displayed offline, although they work. This is a log:
```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/nspanel2.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/6051/head
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from nspanel2.local using esphome API
WARNING Can't connect to ESPHome API for nspanel2.local: Error resolving IP address: [Errno -2] Name or service not known (APIConnectionError)
INFO Trying to connect to nspanel2.local in the background
```

The not working panel is stuck at ESPHome showing retries:
![IMG_20240112_204720](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/34960757/29186aec-c8a7-4f54-86ad-5f7e03b9ea71)

**Comment by andythomas** [comment] 2024-01-12 20:57
I see two things that might or might not mean anything.

1) The name of the panel (`nspanelbuero`) and the name of the yaml (`nspanel2.yaml`) are different. It looks for the panel by the name _in_ the yaml file, but not _of_ the yaml file (as far as I recall). Any chance that this got mixed up? 
2) This kind of mixup happened to me, when I switched from the build-in esphome to my desktop computer which compiles much faster. I assume, you are also using a different computer for HA and the esphome compile, since the path of the configuration is `/config/nspanel2.yaml` and not ` /config/esphome/panel2.yaml`

`INFO Reading configuration /config/nspanel2.yaml...`

**Comment by jimmyhenne** [comment] 2024-01-12 22:51
1. sorry, the log is from one of the running panels. But the log from the broken one is equal except the name. So panelname and matches yaml file name 
`INFO ESPHome 2023.12.5
INFO Reading configuration /config/nspanelbuero.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/6051/head
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from nspanelbuero.local using esphome API
WARNING Can't connect to ESPHome API for nspanelbuero.local: Error resolving IP address: [Errno -2] Name or service not known (APIConnectionError)
INFO Trying to connect to nspanelbuero.local in the background`

2. You are right. HA runs on a small NUC and I use my desktop. That way worked for 2 of 3 panels

**Comment by flodaho** [comment] 2024-01-13 07:25
Same issue hier. Since the update to 4.2 my panel stucks at the same screen. Before everything worked allright. I'll check on your obove ideas and see if i can fix it.

**Comment by edwardtfn** [comment] 2024-01-13 07:30
Try a power cycle or pressing the reset pin behind your device:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/bc90d69a-ea09-4f04-9cec-387f6e3556cb)

**Comment by flodaho** [comment] 2024-01-13 08:37
Thanks for the idea, unfortunately both steps did not help, but i found an interresting behavior: 

1. Stuck situation: according to the boot screen of the panel, TFT version 4.2 is installed and the ESP-Home init does count up retries without success. 

3. I open ESP-Home in HA an re-install the firmware (Validate -> Install) with the following code: 
<img width="593" alt="grafik" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/11586838/9c1990e3-cdbf-4842-bf6f-c78b42058955">

4. --> Panel starts up working with TFT: 4.2 / ESP_Home: 4.2.1 / Blueprint: 4.2.1

5. I start the following service:
<img width="434" alt="grafik" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/11586838/0b761994-0b67-4dbe-b84d-7e9b200a7824">

6. What happens is that the panel shows a Window setting baud rate, .... then the TFT Update screen shows up to immediately change to a incompatibility info screen that says "model does not match device model". 
- The TFT file is correct. I checked couple of times, re-downloaded, ..
- I always did it that way before

7. The mentioned interessting part: after the re-boot it stucks again with the boot screen initializing the ESP-Home version without success. 

This can be reproduced sarting over again. Maybe the bout rate is changed, etc?

**Comment by flodaho** [comment] 2024-01-13 08:41
It also happens this way, without trying to update the TFT file. 

This means:

10 Validate, Install -> works
20 re-boot -> stucks
30 goto 10 ;)

thanks for support, Florian

**Comment by andythomas** [comment] 2024-01-13 09:06
Is it possible that the panel that get stuck was originally flashed with the esp32 framework `arduino` and was now switched to `esp-idf`? Please see [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#framework-esp-idf) for more information. Then, It might need a serial flash.

**Comment by jimmyhenne** [comment] 2024-01-13 09:16
Unfortunately pushing the reset pin didn't help me.
I don't thinkt that I initially flashed arduino as I using the same code sample with esd-idf from the beginning.
I'm also doing serial flashing with an usb ttl driver.

**Comment by edwardtfn** [comment] 2024-01-13 09:28
I don’t think the issue is related to TFT. You have v4.2 installed and that should be fully compatible with v4.2.1.

The problem is on ESPHome side which looks to not be connected to your network or dns is not resolving its name.

Can you double check in your router if you see this device connected? If you see an up address you can try connecting using that, but I don’t think you will find it.

Are you sure the WiFi credentials used are correct? If they aren’t, you should be able to see the fallback access point (a Wi-Fi network with your panels name) that you can check with your phone.

**Comment by edwardtfn** [comment] 2024-01-13 09:31
> Maybe the bout rate is changed, etc?

Tye screen will alternate between 115200 and 921600bps every 30s until ESPHome establishes a connection.

**Comment by blehers** [comment] 2024-01-13 09:37
Same problem here... Is there a possibility to check whether it's flashed with `arduino` or `esp-idf`?

**Comment by edwardtfn** [comment] 2024-01-13 12:46
> Same problem here... Is there a possibility to check whether it's flashed with arduino or esp-idf?

On ESPHome logs, once a minute the watchdog will show this info.
But I don't think this is the same problem as @jimmyhenne reported. In your case ESPHome is communicating with the display, but not with the Blueprint.
I woukd suggest you create another bug so we can focus on the issue you have.

**Comment by jimmyhenne** [comment] 2024-01-13 13:32
> Can you double check in your router if you see this device connected? If you see an up address you can try connecting using that, but I don’t think you will find it.
> 
> Are you sure the WiFi credentials used are correct? If they aren’t, you should be able to see the fallback access point (a Wi-Fi network with your panels name) that you can check with your phone.

I checked the router and the panel and its IP appears as online and active. But I can't get access to it by entering the IP in a browser. I have noticed that the IP isn't shown in the upper left corner of the panel.
The wifi credentials are ok, I checked them. I'm using a secrets.yaml for all panels.

**Comment by edwardtfn** [comment] 2024-01-13 13:50
> I have noticed that the IP isn't shown in the upper left corner of the panel.

This is controlled by ESPHome, so if isn't working properly, it won't show a up on the screen.

**Comment by edwardtfn** [comment] 2024-01-13 13:52
Can you compile the firmware again and flash it to the panel? If so, please add this and then try to connect via web when your panel is on, so you will be able to see logs:

```yaml
web_server:
```

**Comment by jimmyhenne** [comment] 2024-01-13 13:56
Of course, I will flash again. Thanks for your help.
Can you tell me where I have to add web_server: ? Just that tag without any entries?

**Comment by edwardtfn** [comment] 2024-01-13 14:35
It can be at the end of your tank, like this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbuero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://PANEL-IP/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####

web_server:
```

**Comment by edwardtfn** [comment] 2024-01-13 14:38
By the way, this is not the panel ip, but your server ip:

`nextion_update_url: "http://PANEL-IP/local/nspanel_eu.tft" # URL to local tft File`

Like this:

`nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # URL to local tft File`

**Comment by jimmyhenne** [comment] 2024-01-13 15:03
> By the way, this is not the panel ip, but your server ip:

You're right. There is the server IP entered; I just put in a wrong placeholder.

I have now flashed with web_server and can access the panel and can see a log on the right side.
Can I save the whole file?
I copied some files I think could be helpful.

```
15:57:05	[W]	[nextion:081]	

Nextion is not connected! 

15:57:06	[W]	[nextion:081]	

Nextion is not connected! 

15:57:06	[W]	[nextion:081]	

Nextion is not connected! 

15:57:07	[W]	[nextion:081]	

Nextion is not connected! 

15:57:29	[W]	[nextion:081]	

Nextion is not connected! 

15:57:29	[W]	[nextion:081]	

Nextion is not connected! 

15:57:30	[W]	[nextion:081]	

Nextion is not connected! 

15:57:30	[I]	[script.watchdog:3103]	

Wi-Fi:         Good (-51 dBm)

15:57:30	[I]	[script.watchdog:3123]	

API:           Connected

15:57:30	[W]	[script.watchdog:3143]	

Blueprint:     Pending

15:57:30	[I]	[script.watchdog:3144]	

Requesting blueprint settings

15:57:30	[I]	[script.watchdog:3154]	

ESPHome:

15:57:30	[I]	[script.watchdog:3155]	

  Version:     4.2.1

15:57:30	[I]	[script.watchdog:3160]	

  Framework:   esp-idf

15:57:30	[I]	[script.watchdog:3164]	

UART:

15:57:30	[I]	[script.watchdog:3165]	

  Baud rate:   115200 bps

15:57:30	[I]	[script.watchdog:3166]	

  Queue size:  0

15:57:30	[I]	[script.watchdog:3170]	

Nextion:

15:57:30	[I]	[script.watchdog:3171]	

  Queue size:  0

15:57:30	[W]	[script.watchdog:3175]	

  Is setup:    False

15:57:30	[W]	[script.watchdog:3176]	

  Is detected: False

15:57:30	[W]	[script.watchdog:3184]	

  Init:        False

15:57:30	[W]	[script.watchdog:3186]	

  TFT:         UNKNOWN

15:57:30	[W]	[nextion:081]	

Nextion is not connected! 

15:57:31	[W]	[nextion:081]	

Nextion is not connected!
```

**Comment by geni0602** [comment] 2024-01-13 16:40
I had the same log, eventually after 6-7 min. It ot a connected. After restart there was the same issue nextion not connected.
Maybe the issue came with the change to esp-idf. I've changed from Arduino with OTA update. After that I flashed over Serial (how to docs) but still no connection. 

If I flash with serial, should I erase the flash before flashing? 

Only thing that helped was downgrading back to 4.1.4 (Arduino). With 4.1.4 everything is working fine

**Comment by jimmyhenne** [comment] 2024-01-13 20:55
It's strange. I flashed two more times and at last I deleted the ESPHome device and restarted HA. Plugged in panel again and after 10 retries it is connected. Unplugged and plugged it again and it takes 10 attempts again but then its ok.

**Comment by geni0602** [comment] 2024-01-13 21:20
> It's strange. I flashed two more times and at last I deleted the ESPHome device and restarted HA. Plugged in panel again and after 10 retries it is connected. Unplugged and plugged it again and it takes 10 attempts again but then its ok.

What do you mean with 10 times? You get 10 times the message nextion not connected in your log and after that in connects? 

Then I will also try to erase the esp-flash before flashing with 4.2.1 and esp-idf

**Comment by jimmyhenne** [comment] 2024-01-13 21:25
I mean the boot screen of the panel. There were shown Retries to initialise ESPHome connection. See the picture I posted before
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1614#issuecomment-1889924351

**Comment by geni0602** [comment] 2024-01-13 21:27
Ah ok thanks. How long does it last to load the home page after restarting?

**Comment by jimmyhenne** [comment] 2024-01-13 21:28
I didn't measure the time it takes. I estimate 2 minutes.

**Comment by edwardtfn** [comment] 2024-01-13 21:37
> Plugged in panel again and after 10 retries it is connected. Unplugged and plugged it again and it takes 10 attempts again but then its ok.

Mmmmm
I have to investigate this.

**Comment by jimmyhenne** [comment] 2024-01-13 22:52
Can I contribute any further information?

**Comment by edwardtfn** [comment] 2024-01-14 07:19
If you can still duplicate the issue, I will work in a solution and when I get to something I will love if you can give a try and let me know if the problem persists or disappeared. 😉 

For now, if you have more details on how to replicate it (a detailed step by step) it would be great, as I couldn't replicate it here, yet.

**Comment by geni0602** [comment] 2024-01-14 07:32
> If you can still duplicate the issue, I will work in a solution and when I get to something I will love if you can give a try and let me know if the problem persists or disappeared. 😉
> 
> For now, if you have more details on how to replicate it (a detailed step by step) it would be great, as I couldn't replicate it here, yet.

For me it was pretty easy to replicate: I had 4.1.4 Arduino. Made an update OTA to 4.2.1 and changed to esp-idf. Then I updated the TFT to 4.2.1 ( from this new drop down menu) and after that there was no nextion connection. Eventually it gets connected after 6-7 min. 

Serial flashing didn't help.

**Comment by edwardtfn** [comment] 2024-01-14 07:33
I will try that.

**Comment by geni0602** [comment] 2024-01-14 07:58
i´ve just updated again and now it looks fine.  My panel has sometimes Problems with my Unifi AP, even though the AP is in only 1m distance. I´ve locked the panel to another AP in my house (same credentials) and flashed again. Booting time 20-30 sec., just like before

th 0 decimals of accuracy
[08:53:30][I][script.watchdog:3103]: Wi-Fi:         Fair (-68 dBm)
[08:53:30][I][script.watchdog:3123]: API:           Connected
[08:53:30][I][script.watchdog:3141]: Blueprint:     4.2.1
[08:53:30][I][script.watchdog:3154]: ESPHome:
[08:53:30][I][script.watchdog:3155]:   Version:     4.2.1
[08:53:30][I][script.watchdog:3160]:   Framework:   esp-idf
[08:53:30][I][script.watchdog:3164]: UART:
[08:53:30][I][script.watchdog:3165]:   Baud rate:   115200 bps
[08:53:30][I][script.watchdog:3166]:   Queue size:  12
[08:53:30][I][script.watchdog:3170]: Nextion:
[08:53:30][I][script.watchdog:3171]:   Queue size:  3
[08:53:30][I][script.watchdog:3173]:   Is setup:    True
[08:53:30][I][script.watchdog:3180]:   Init:        True
[08:53:30][I][script.watchdog:3188]:   TFT:         4.2.1
[08:53:36][D][sensor:094]: 'ntc_source': Sending state 1.67600 V with 2 decimals

**Comment by edwardtfn** [comment] 2024-01-14 08:26
> Eventually it gets connected after 6-7 min.

The watchdog is probably restarting the display after a while and this is fixing the issue.
Can you see the display turning off right before it gets connected?

**Comment by geni0602** [comment] 2024-01-14 09:26
I've just flashed my second one. Same way OTA Update with change to esp-idf and got the same issue as the first one "nextion not connected". I didn't have analyze and check the logs details. I'll make it later. 

I have a third Panel and I will update it at first without changing the framework to esp-ifd, see what happens

**Comment by jimmyhenne** [comment] 2024-01-14 09:34
> If you can still duplicate the issue, I will work in a solution and when I get to something I will love if you can give a try and let me know if the problem persists or disappeared. 😉
>
I'm afraid I can't help you completely because I don't know how to duplicate. But since the problem has not been fixed completely for me (takes 10 retry cycles), I can test possible solutions.

**Comment by geni0602** [comment] 2024-01-14 14:29
i´ve just updated my last panel OTA to 4.2.1 without changing the framework to esp-idf and there was no issue at all. 
1. ESP-Update
2. Upload TFT 
No errors at all. Boot was as always. 

Is it mandatory to flash with Serial, if you want to change to esp-idf?



Logs:

INFO Successfully connected to nspanel_studio @ 192.168.1.151 in 0.126s
INFO Successful handshake with nspanel_studio @ 192.168.1.151 in 0.067s
[15:24:00][D][sensor:094]: 'ntc_source': Sending state 1.80600 V with 2 decimals of accuracy
[15:24:00][D][resistance:039]: 'resistance_sensor' - Resistance 13539.0Ω
[15:24:00][D][sensor:094]: 'resistance_sensor': Sending state 13538.95605 Ω with 1 decimals of accuracy
[15:24:00][D][ntc:026]: 'nspanel_studio Temperature' - Temperature: 18.3°C
[15:24:00][D][sensor:094]: 'nspanel_studio Temperature': Sending state 18.33385 °C with 1 decimals of accuracy
[15:24:05][I][addon_upload_tft.script.report_settings:189]: TFT URL: http://192.168.1.30:8123/local/nspanel_eu.tft
[15:24:05][I][addon_upload_tft.script.report_settings:190]: Substitutions:
[15:24:05][I][addon_upload_tft.script.report_settings:191]:   nextion_update_url:        http://192.168.1.30:8123/local/nspanel_eu.tft
[15:24:05][I][addon_upload_tft.script.report_settings:192]:   nextion_update_base_url:   https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/
[15:24:05][I][addon_upload_tft.script.report_settings:193]:   upload_tft_chunk_size_max: 32768
[15:24:05][I][addon_upload_tft.script.report_settings:194]:   upload_tft_baud_rate:      921600
[15:24:10][D][sensor:094]: 'nspanel_studio RSSI': Sending state -64.00000 dBm with 0 decimals of accuracy
[15:24:19][D][script.set_brightness:2496]: brightness: 10%
[15:24:30][I][script.watchdog:3103]: Wi-Fi:         Fair (-64 dBm)
[15:24:30][I][script.watchdog:3123]: API:           Connected
[15:24:30][I][script.watchdog:3141]: Blueprint:     4.2.1
[15:24:30][I][script.watchdog:3154]: ESPHome:
[15:24:30][I][script.watchdog:3155]:   Version:     4.2.1
[15:24:30][I][script.watchdog:3158]:   Framework:   arduino
[15:24:30][I][script.watchdog:3164]: UART:
[15:24:30][I][script.watchdog:3165]:   Baud rate:   115200 bps
[15:24:30][I][script.watchdog:3166]:   Queue size:  8
[15:24:30][I][script.watchdog:3170]: Nextion:
[15:24:30][I][script.watchdog:3171]:   Queue size:  2
[15:24:30][I][script.watchdog:3173]:   Is setup:    True
[15:24:30][I][script.watchdog:3180]:   Init:        True
[15:24:30][I][script.watchdog:3188]:   TFT:         4.2.1
[15:25:00][D][sensor:094]: 'ntc_source': Sending state 1.80300 V with 2 decimals of accuracy
[15:25:00][D][resistance:039]: 'resistance_sensor' - Resistance 13489.4Ω
[15:25:00][D][sensor:094]: 'resistance_sensor': Sending state 13489.37793 Ω with 1 decimals of accuracy
[15:25:00][D][ntc:026]: 'nspanel_studio Temperature' - Temperature: 18.4°C
[15:25:00][D][sensor:094]: 'nspanel_studio Temperature': Sending state 18.41278 °C with 1 decimals of accuracy
[15:25:10][D][sensor:094]: 'nspanel_studio RSSI': Sending state -64.00000 dBm with 0 decimals of accuracy
[15:25:30][I][script.watchdog:3103]: Wi-Fi:         Fair (-64 dBm)
[15:25:30][I][script.watchdog:3123]: API:           Connected
[15:25:30][I][script.watchdog:3141]: Blueprint:     4.2.1
[15:25:30][I][script.watchdog:3154]: ESPHome:
[15:25:30][I][script.watchdog:3155]:   Version:     4.2.1
[15:25:30][I][script.watchdog:3158]:   Framework:   arduino
[15:25:30][I][script.watchdog:3164]: UART:
[15:25:30][I][script.watchdog:3165]:   Baud rate:   115200 bps
[15:25:30][I][script.watchdog:3166]:   Queue size:  8
[15:25:30][I][script.watchdog:3170]: Nextion:
[15:25:30][I][script.watchdog:3171]:   Queue size:  2
[15:25:30][I][script.watchdog:3173]:   Is setup:    True
[15:25:30][I][script.watchdog:3180]:   Init:        True
[15:25:30][I][script.watchdog:3188]:   TFT:         4.2.1
[15:26:00][D][sensor:094]: 'ntc_source': Sending state 1.79100 V with 2 decimals of accuracy
[15:26:00][D][resistance:039]: 'resistance_sensor' - Resistance 13293.0Ω
[15:26:00][D][sensor:094]: 'resistance_sensor': Sending state 13293.04297 Ω with 1 decimals of accuracy
[15:26:00][D][ntc:026]: 'nspanel_studio Temperature' - Temperature: 18.7°C
[15:26:00][D][sensor:094]: 'nspanel_studio Temperature': Sending state 18.72866 °C with 1 decimals of accuracy
[15:26:10][D][sensor:094]: 'nspanel_studio RSSI': Sending state -64.00000 dBm with 0 decimals of accuracy
[15:26:23][I][ota:117]: Boot seems successful, resetting boot loop counter.
[15:26:23][D][esp32.preferences:114]: Saving 1 preferences to flash...
[15:26:23][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[15:26:30][I][script.watchdog:3103]: Wi-Fi:         Fair (-64 dBm)
[15:26:30][I][script.watchdog:3123]: API:           Connected
[15:26:30][I][script.watchdog:3141]: Blueprint:     4.2.1
[15:26:30][I][script.watchdog:3154]: ESPHome:
[15:26:30][I][script.watchdog:3155]:   Version:     4.2.1
[15:26:30][I][script.watchdog:3158]:   Framework:   arduino
[15:26:30][I][script.watchdog:3164]: UART:
[15:26:30][I][script.watchdog:3165]:   Baud rate:   115200 bps
[15:26:30][I][script.watchdog:3166]:   Queue size:  8
[15:26:30][I][script.watchdog:3170]: Nextion:
[15:26:30][I][script.watchdog:3171]:   Queue size:  2
[15:26:30][I][script.watchdog:3173]:   Is setup:    True
[15:26:30][I][script.watchdog:3180]:   Init:        True
[15:26:30][I][script.watchdog:3188]:   TFT:         4.2.1

**Comment by edwardtfn** [comment] 2024-01-14 16:19
> Is it mandatory to flash with Serial, if you want to change to esp-idf?

It is highly recommended, otherwise you can get issues at the boot.

But if you cannot do a serial flash now, just stay with `arduino` as that still supported. We are planning to make `esp-idf` default, but the support to arduino may remain for a longer time.

**Comment by geni0602** [comment] 2024-01-14 16:31
> > Is it mandatory to flash with Serial, if you want to change to esp-idf?
> 
> It is highly recommended, otherwise you can get issues at the boot.
> 
> But if you cannot do a serial flash now, just stay with `arduino` as that still supported. We are planning to make `esp-idf` default, but the support to arduino may remain for a longer time.

Thanks. I've flashed one over serial to esp-idf and the rest is on Arduino.

**Closed** 2024-01-15 12:41 UTC
Labels: Bug, Solved, Page: boot
