### ISSUE TITLE
1 Panel out of 15 not updating - reporting using unknown service 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1644] opened 2024-01-16 10:18 UTC
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

Panel seems to flash but starts update at 75% on the progress bar. Then unknown service reported 

### Steps to Reproduce

Updated all panels. This is the last. It had an old version on it as it has not yet been installed.

Flashes over USB. On update it starts from 75% progress bar.

I then re flashed it by USB. Same. Wirelessly. Same. NsPanel Blank - Same.

On boot it reports begin on version 4.2.1 but the screen just has the time and temp on it.

The blueprint is reporting 

Panel - Bar uses an unknown service
The automation "Panel - Bar" (automation.panel_bar) has an action that calls an unknown service: esphome.barpanel_send_command_printf.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.20.177:8123/config/automation/edit/1705399156510) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.

The blueprint has been 

1. copied from another working one - same
2. Re created as a fresh blueprint - same

I dint think this is the blueprint but something about how the unit is flashing given update starts all the time at 75%. The strange thing it that it then reports on boot that it is on the most recent version.

Any suggestions ? All the other panels are fine and the process followed is identical for all of them,

Thank you 

### Your panel's YAML

```yaml
ubstitutions:

###### CHANGE ME START ######

  device_name: "barpanel" 
  wifi_ssid: "Automation"
  wifi_password: "xxxx"

  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

    # Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600
```

### ESPHome logs

```logs
INFO ESPHome 2023.12.6
INFO Reading configuration /config/esphome/bar.yaml...
INFO Detected timezone 'Europe/London'
INFO Starting log output from 192.168.20.5 using esphome API
INFO Successfully connected to barpanel @ 192.168.20.5 in 0.003s
INFO Successful handshake with barpanel @ 192.168.20.5 in 0.029s
[10:11:53][W][component:214]: Component api took a long time for an operation (0.06 s).
[10:11:53][W][component:215]: Components should block for at most 20-30ms.
[10:11:53][I][app:102]: ESPHome version 2023.12.6 compiled on Jan 16 2024, 09:46:11
[10:11:53][C][wifi:573]: WiFi:
[10:11:53][C][wifi:405]:   Local MAC: C0:49:EF:D3:E3:18
[10:11:53][C][wifi:410]:   SSID: 'Automation'[redacted]
[10:11:53][C][wifi:411]:   IP Address: 192.168.20.5
[10:11:53][C][wifi:413]:   BSSID: 70:A7:41:76:BF:A0[redacted]
[10:11:53][C][wifi:414]:   Hostname: 'barpanel'
[10:11:53][C][wifi:416]:   Signal strength: -66 dB ▂▄▆█
[10:11:53][C][wifi:420]:   Channel: 11
[10:11:53][C][wifi:421]:   Subnet: 255.255.255.0
[10:11:53][C][wifi:422]:   Gateway: 192.168.20.1
[10:11:53][C][wifi:423]:   DNS1: 192.168.20.1
[10:11:53][C][wifi:424]:   DNS2: 0.0.0.0
[10:11:53][C][logger:439]: Logger:
[10:11:53][C][logger:440]:   Level: DEBUG
[10:11:53][C][logger:441]:   Log Baud Rate: 0
[10:11:53][C][logger:443]:   Hardware UART: UART0
[10:11:53][C][uart.idf:139]: UART Bus 0:
[10:11:53][C][uart.idf:140]:   TX Pin: GPIO16
[10:11:53][C][uart.idf:141]:   RX Pin: GPIO17
[10:11:53][C][uart.idf:143]:   RX Buffer Size: 256
[10:11:53][C][uart.idf:145]:   Baud Rate: 115200 baud
[10:11:53][C][uart.idf:146]:   Data Bits: 8
[10:11:53][C][uart.idf:147]:   Parity: NONE
[10:11:53][C][uart.idf:148]:   Stop bits: 1
[10:11:53][C][ledc.output:164]: LEDC Output:
[10:11:53][C][ledc.output:165]:   Pin GPIO21
[10:11:53][C][ledc.output:166]:   LEDC Channel: 0
[10:11:53][C][ledc.output:167]:   PWM Frequency: 1000.0 Hz
[10:11:53][C][ledc.output:168]:   Bit depth: 16
[10:11:53][C][template.binary_sensor:028]: Template Binary Sensor 'barpanel Nextion display'
[10:11:53][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[10:11:53][C][template.number:050]: Template Number 'barpanel Display Brightness'
[10:11:53][C][template.number:050]:   Unit of Measurement: '%'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Display Brightness Dimdown'
[10:11:53][C][template.number:050]:   Unit of Measurement: '%'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Display Brightness Sleep'
[10:11:53][C][template.number:050]:   Unit of Measurement: '%'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Temperature Correction'
[10:11:53][C][template.number:050]:   Unit of Measurement: '°C'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Timeout Page'
[10:11:53][C][template.number:050]:   Icon: 'mdi:timer'
[10:11:53][C][template.number:050]:   Unit of Measurement: 's'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Timeout Dimming'
[10:11:53][C][template.number:050]:   Icon: 'mdi:timer'
[10:11:53][C][template.number:050]:   Unit of Measurement: 's'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.number:050]: Template Number 'barpanel Timeout Sleep'
[10:11:53][C][template.number:050]:   Icon: 'mdi:timer'
[10:11:53][C][template.number:050]:   Unit of Measurement: 's'
[10:11:53][C][template.number:051]:   Optimistic: YES
[10:11:53][C][template.number:052]:   Update Interval: 60.0s
[10:11:53][C][template.select:065]: Template Select 'barpanel Baud rate'
[10:11:53][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[10:11:53][C][template.select:066]:   Update Interval: 60.0s
[10:11:53][C][template.select:069]:   Optimistic: YES
[10:11:53][C][template.select:070]:   Initial Option: 115200
[10:11:53][C][template.select:071]:   Restore Value: YES
[10:11:53][C][template.select:065]: Template Select 'barpanel Wake-up page'
[10:11:53][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[10:11:53][C][template.select:066]:   Update Interval: 60.0s
[10:11:53][C][template.select:069]:   Optimistic: YES
[10:11:53][C][template.select:070]:   Initial Option: home
[10:11:53][C][template.select:071]:   Restore Value: YES
[10:11:53][C][template.select:065]: Template Select 'barpanel Update TFT display - Branch'
[10:11:53][C][template.select:065]:   Icon: 'mdi:file-sync'
[10:11:53][C][template.select:066]:   Update Interval: 60.0s
[10:11:53][C][template.select:069]:   Optimistic: YES
[10:11:53][C][template.select:070]:   Initial Option: main
[10:11:53][C][template.select:071]:   Restore Value: YES
[10:11:53][C][template.select:065]: Template Select 'barpanel Update TFT display - Model'
[10:11:53][C][template.select:065]:   Icon: 'mdi:file-sync'
[10:11:53][C][template.select:066]:   Update Interval: 60.0s
[10:11:53][C][template.select:069]:   Optimistic: YES
[10:11:53][C][template.select:070]:   Initial Option: Use nextion_update_url
[10:11:53][C][template.select:071]:   Restore Value: YES
[10:11:53][C][template.text_sensor:020]: Template Sensor 'barpanel Detailed Entity'
[10:11:53][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[10:11:53][C][template.text_sensor:020]: Template Sensor 'barpanel Current page'
[10:11:53][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[10:11:53][C][template.text_sensor:020]: Template Sensor 'barpanel Notification Label'
[10:11:53][C][template.text_sensor:020]: Template Sensor 'barpanel Notification Text'
[10:11:53][C][switch.gpio:068]: GPIO Switch 'barpanel Relay 1'
[10:11:53][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[10:11:53][C][switch.gpio:031]:   Pin: GPIO22
[10:11:53][C][switch.gpio:068]: GPIO Switch 'barpanel Relay 2'
[10:11:53][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[10:11:53][C][switch.gpio:031]:   Pin: GPIO19
[10:11:54][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'barpanel Left Button'
[10:11:54][C][gpio.binary_sensor:016]:   Pin: GPIO14
[10:11:54][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'barpanel Right Button'
[10:11:54][C][gpio.binary_sensor:016]:   Pin: GPIO27
[10:11:54][C][switch.gpio:068]: GPIO Switch 'barpanel Nextion display - Power'
[10:11:54][C][switch.gpio:091]:   Restore Mode: always ON
[10:11:54][C][switch.gpio:031]:   Pin: GPIO4
[10:11:54][C][template.switch:068]: Template Switch 'barpanel Notification sound'
[10:11:54][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[10:11:54][C][template.switch:057]:   Optimistic: YES
[10:11:54][C][template.switch:068]: Template Switch 'barpanel Relay 1 Local'
[10:11:54][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[10:11:54][C][template.switch:057]:   Optimistic: YES
[10:11:54][C][template.switch:068]: Template Switch 'barpanel Relay 2 Local'
[10:11:54][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[10:11:54][C][template.switch:057]:   Optimistic: YES
[10:11:54][C][template.switch:068]: Template Switch 'barpanel Notification unread'
[10:11:54][C][template.switch:091]:   Restore Mode: always OFF
[10:11:54][C][template.switch:057]:   Optimistic: YES
[10:11:54][C][rtttl:029]: Rtttl
[10:11:54][C][nextion:128]: Nextion:
[10:11:54][C][nextion:129]:   Device Model:     NX4832F035_011C
[10:11:54][C][nextion:130]:   Firmware Version: 72
[10:11:54][C][nextion:131]:   Serial Number:    F18B3401718BE460
[10:11:54][C][nextion:132]:   Flash Size:       16777216
[10:11:54][C][nextion:133]:   Wake On Touch:    YES
[10:11:54][C][nextion:134]:   Exit reparse:     YES
[10:11:54][C][restart.button:017]: Restart Button 'barpanel Restart'
[10:11:54][C][adc:097]: ADC Sensor 'ntc_source'
[10:11:54][C][adc:097]:   Device Class: 'voltage'
[10:11:54][C][adc:097]:   State Class: 'measurement'
[10:11:54][C][adc:097]:   Unit of Measurement: 'V'
[10:11:54][C][adc:097]:   Accuracy Decimals: 2
[10:11:54][C][adc:107]:   Pin: GPIO38
[10:11:54][C][adc:122]:  Attenuation: 11db
[10:11:54][C][adc:142]:   Update Interval: 60.0s
[10:11:54][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[10:11:54][C][resistance:010]:   State Class: 'measurement'
[10:11:54][C][resistance:010]:   Unit of Measurement: 'Ω'
[10:11:54][C][resistance:010]:   Accuracy Decimals: 1
[10:11:54][C][resistance:010]:   Icon: 'mdi:flash'
[10:11:54][C][resistance:011]:   Configuration: DOWNSTREAM
[10:11:54][C][resistance:012]:   Resistor: 11200.00Ω
[10:11:54][C][resistance:013]:   Reference Voltage: 3.3V
[10:11:55][C][ntc:014]: NTC Sensor 'barpanel Temperature'
[10:11:55][C][ntc:014]:   Device Class: 'temperature'
[10:11:55][C][ntc:014]:   State Class: 'measurement'
[10:11:55][C][ntc:014]:   Unit of Measurement: '°C'
[10:11:55][C][ntc:014]:   Accuracy Decimals: 1
[10:11:55][C][homeassistant.time:010]: Home Assistant Time:
[10:11:55][C][homeassistant.time:011]:   Timezone: 'GMT0BST,M3.5.0/1,M10.5.0'
[10:11:55][C][status:034]: Status Binary Sensor 'barpanel Status'
[10:11:55][C][status:034]:   Device Class: 'connectivity'
[10:11:56][C][mdns:115]: mDNS:
[10:11:56][C][mdns:116]:   Hostname: barpanel
[10:11:56][C][ota:097]: Over-The-Air Updates:
[10:11:56][C][ota:098]:   Address: barpanel.local:3232
[10:11:56][C][ota:101]:   Using Password.
[10:11:56][C][api:139]: API Server:
[10:11:56][C][api:140]:   Address: barpanel.local:6053
[10:11:56][C][api:144]:   Using noise encryption: NO
[10:11:56][C][wifi_signal.sensor:009]: WiFi Signal 'barpanel RSSI'
[10:11:56][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[10:11:56][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[10:11:56][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[10:11:56][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
```

### Home Assistant logs

```logs
Home Assistant Core


Panel - Bar: Main choices: NSPanel event: Choose at step 2: Boot init: If at step 1: If at step 7: Error executing script. Service not found for call_service at pos 3: Service esphome.barpanel_send_command_text_printf not found.
10:12:13 – (ERROR) Automation - message first occurred at 09:29:16 and shows up 435 times
topstairstop @ 192.168.20.124: Connection error occurred: Ping response not received after 90.0 seconds
10:06:57 – (WARNING) runner.py - message first occurred at 15 January 2024, 10:22:37 and shows up 134 times
Uncaught error from Safari 14.1.2 on Mac OS 10.14.6 Script error. null @:0:0
10:05:46 – (ERROR) components/system_log/__init__.py - message first occurred at 15 January 2024, 10:45:33 and shows up 15 times
Platform automation does not generate unique IDs. ID 1683222236170 already exists - ignoring automation.topstairsfirst_2
10:03:17 – (ERROR) Automation - message first occurred at 15 January 2024, 10:17:06 and shows up 33 times
Error while executing automation automation.study: AttributeError: 'list' object has no attribute 'lower'
09:52:47 – (ERROR) Automation
Panel - Study: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:52:47 – (ERROR) Automation - message first occurred at 09:52:47 and shows up 5 times
Error while executing automation automation.panel_side_door: extra keys not allowed @ data['meridiem']
09:50:28 – (ERROR) Automation - message first occurred at 15 January 2024, 17:07:04 and shows up 11 times
Panel - Side Door: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:50:28 – (ERROR) Automation - message first occurred at 15 January 2024, 17:07:04 and shows up 37 times
Error while executing automation automation.panel_musicroom: AttributeError: 'list' object has no attribute 'lower'
09:48:11 – (ERROR) Automation
Panel - Musicroom: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:48:11 – (ERROR) Automation - message first occurred at 09:48:11 and shows up 5 times
Can't connect to ESPHome API for masterlounge @ 192.168.20.66: Hello timed out (TimeoutAPIError)
09:47:19 – (WARNING) runner.py - message first occurred at 15 January 2024, 10:17:07 and shows up 47 times
Timeout connecting to http://192.168.20.9/status [shellyrgbw2-D8A565]
09:46:19 – (ERROR) /usr/local/lib/python3.11/site-packages/pyShelly/utils.py - message first occurred at 09:46:19 and shows up 3 times
Error while executing automation automation.masterbed2: extra keys not allowed @ data['meridiem']
09:45:30 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:44 and shows up 13 times
Panel - Masterbed 2: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:45:30 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:44 and shows up 47 times
Error while executing automation automation.master_bedroom_lounge_ns_panel: extra keys not allowed @ data['meridiem']
09:43:15 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:16 and shows up 13 times
Panel - Master Bedroom Lounge : Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:43:15 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:16 and shows up 47 times
Error while executing automation automation.entrance_door: extra keys not allowed @ data['meridiem']
09:42:58 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:56 and shows up 14 times
Panel - Entrance Door: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:42:58 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:56 and shows up 53 times
Error while executing automation automation.master_bed_panel: extra keys not allowed @ data['meridiem']
09:40:30 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:20 and shows up 8 times
Panel - Master Bed: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:40:30 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:20 and shows up 35 times
Error while executing automation automation.lounge: extra keys not allowed @ data['meridiem']
09:40:10 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:52 and shows up 9 times
Panel - lounge: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:40:10 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:52 and shows up 41 times
Error while executing automation automation.automation_33: AttributeError: 'list' object has no attribute 'lower'
09:37:52 – (ERROR) Automation
Panel - Kitchen2: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:37:52 – (ERROR) Automation - message first occurred at 09:37:52 and shows up 5 times
Error while executing automation automation.kitchen: extra keys not allowed @ data['meridiem']
09:35:35 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:24 and shows up 7 times
Panel - Kitchen : Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:35:35 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:24 and shows up 31 times
Error while executing automation automation.front_door: extra keys not allowed @ data['meridiem']
09:33:19 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:48 and shows up 16 times
Panel - Ground Floor Stairs: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:33:19 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:48 and shows up 83 times
Unable to find entity light.cinema_tv_left
09:29:39 – (WARNING) Light - message first occurred at 09:29:39 and shows up 2 times
Error while executing automation automation.cinema: extra keys not allowed @ data['meridiem']
09:29:26 – (ERROR) Automation - message first occurred at 15 January 2024, 17:08:21 and shows up 19 times
Panel - cinema: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:29:26 – (ERROR) Automation - message first occurred at 15 January 2024, 17:08:21 and shows up 83 times
While executing automation automation.cinema
09:28:28 – (ERROR) Automation
Panel - cinema: Main choices: Automation reloaded: If at step 3: Error executing script. Unexpected error for call_service at pos 5: '>=' not supported between instances of 'NoneType' and 'APIVersion'
09:28:28 – (ERROR) Automation - message first occurred at 09:28:28 and shows up 3 times
Panel - Bar: Main choices: NSPanel event: Choose at step 2: Boot init: If at step 1: If at step 7: Error executing script. Service not found for call_service at pos 3: Service esphome.barpanel_send_command_text_printf not found.
09:27:30 – (ERROR) Automation - message first occurred at 09:23:19 and shows up 58 times
Unable to remove unknown service esphome/barpanel_send_command_font_color
09:16:34 – (WARNING) core.py - message first occurred at 09:16:34 and shows up 10 times
Error while executing automation automation.topstairsfirst_2: extra keys not allowed @ data['meridiem']
09:05:48 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:36 and shows up 16 times
Panel - topstairsfirst: Main choices: NSPanel event: Choose at step 2: Page changed: Choose at step 1: Home page: If at step 4: Error executing script. Error rendering template for variables at pos 1: AttributeError: 'list' object has no attribute 'lower'
09:05:48 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:36 and shows up 69 times
Unable to find entity switch.sonoff_10003704f1
08:54:59 – (WARNING) Switch - message first occurred at 15 January 2024, 15:46:01 and shows up 14 times
Error while executing automation automation.topstairstop: extra keys not allowed @ data['meridiem']
08:48:56 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:40 and shows up 10 times
Panel - topstairstop: Main choices: Automation reloaded: If at step 3: Error executing script. Invalid data for call_service at pos 5: extra keys not allowed @ data['meridiem']
08:48:56 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:40 and shows up 30 times
MOTION - Hall Day Time : Already running
08:16:22 – (WARNING) Automation
[Errno 104] Connection reset by peer - goodbye
07:38:41 – (ERROR) /usr/local/lib/python3.11/site-packages/websocket/_logging.py - message first occurred at 15 January 2024, 10:58:14 and shows up 26 times
Invalid state specified for switch.master_lounge_lamps: unavailable
03:20:01 – (WARNING) Switch - message first occurred at 15 January 2024, 22:12:59 and shows up 2 times
Invalid state specified for light.hall_bookcase_left: unavailable
03:20:01 – (WARNING) Light - message first occurred at 15 January 2024, 15:51:15 and shows up 12 times
Error fetching roborock data: id=11284 Timeout after 4 seconds
03:16:33 – (ERROR) Roborock - message first occurred at 15 January 2024, 10:59:14 and shows up 6 times
Error doing job: Task exception was never retrieved
03:14:45 – (ERROR) components/unifiprotect/data.py - message first occurred at 03:14:10 and shows up 8 times
Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsps://192.168.1.1:7441/uGnBKJTlQ4IIsr9e?enableSrtp'; last error log: [tls] The specified session has been invalidated for some reason.
03:14:41 – (ERROR) Stream - message first occurred at 03:05:13 and shows up 11 times
Error fetching device events data: Failed to connect.
03:12:27 – (ERROR) Overkiz - message first occurred at 03:08:03 and shows up 2 times
[Top floor] Client or broker did not communicate in the keepalive interval.
03:09:02 – (WARNING) /usr/local/lib/python3.11/site-packages/roborock/api.py - message first occurred at 03:08:30 and shows up 4 times
Error doing job: Task exception was never retrieved
03:08:59 – (ERROR) /usr/src/homeassistant/homeassistant/runner.py
 
CLEAR
```

**Comment by edwardtfn** [comment] 2024-01-16 16:26
> 09:40:30 – (ERROR) Automation - message first occurred at 15 January 2024, 17:06:20 and shows up 35 times
Error while executing automation automation.lounge: extra keys not allowed @ data['meridiem']

This is odd. Are you sure you got this message after the update? I would expect that if the Blueprint was v4.2.x but ESPHome was still in an earlier version.

> The blueprint has been
> 1. copied from another working one - same
> 2. Re created as a fresh blueprint - same

This shouldn't be an issue, but if you have change some entity name in your panel I would expect that error you mentioned. In order to fix that, try to remove your panel from the HA integrations (Settings > Devices and Services > ESPHome), then restart HA and add your panel again (if your panel was not detected automatically, click on Add integration button and then select ESPHome).
Note: Don't remove your panel from ESPHome Dashboard, it is only from integrations in Home Assistant.

**Comment by edwardtfn** [comment] 2024-01-25 20:47
@rudgej, are you still having this issue?

**Comment by edwardtfn** [comment] 2024-01-29 06:28
I'm closing this as it is quiet.

**Closed by edwardtfn** 2024-01-29 06:28 UTC
Labels: Bug, Validation pending

**Comment by grigi** [comment] 2024-02-12 13:54
I'm having the same issue after updating to 4.2.5
Downgrading to 4.2.4 fixes everything.

I suspect it has to do with me defining a friendly name in the ESPHome config.
The blueprint thinks all the service names changed from `nspanel_01_*` to `nspanel_study_*` because I defined a friendly name.

I removed the panel from the esphome integration and had it re-discovered and added. This changed nothing.

The blueprint should use the device name name for service names as that is what the ESPHome integration does.

**Comment by grigi** [comment] 2024-02-12 14:07
Confirmed that removing the friendly_name in ESPHome yaml, re-adding it, fixes it.
Then I went and change the name of the device in HA, and it asked to update the entity names, I said yes, and it didn't seem to change the service names that I could see.

but it works as long as friendly_name is not defined in the yaml any more

**Comment by edwardtfn** [comment] 2024-02-12 14:26
> The blueprint should use the device name name for service names as that is what the ESPHome integration does.

This is what it was supposed to be doing.
Have you updated the blueprint also to v4.2.5 to test that?
I will have to investigate it.

**Comment by grigi** [comment] 2024-02-12 18:06
Everything (including the TFT) was on v4.2.5

Although when I updated ESPHome to 4.2.5 it failed with the blueprint which was 4.2.4 at that time, so possibly this bug may only be uncovered now.

**Comment by edwardtfn** [comment] 2024-02-12 18:51
Do you mind reporting a bug specifically about this thing with friendly name? It's quite hard to keep control when the topic deviates from the original one like here.

**Comment by grigi** [comment] 2024-02-12 19:03
I posted it here because the symptoms were the closest I could find, but yeah, I see your point.
