### ISSUE TITLE
Can't connect to Nextion after flashing TFT

### ISSUE THREAD

**Issue by Jelle-Tigchelaar** [Blackymas/NSPanel_HA_Blueprint#107] opened 2022-12-13 19:08 UTC
I uploaded the code through ESPHOME succesfully, I then connected to the device through WiFi and toggled the 'Update TFT display'.
That ran through the update cycle and the device rebooted, I can see the 'Initializing' screen with the Home Assistant, but it remains stuck there. When I look at the logs, it keeps showing this error:

```
:05:18 | [W] | [nextion:078] | Nextion is not connected!
20:05:19 | [W] | [nextion:078] | Nextion is not connected!
20:05:19 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:05:19 | [W] | [nextion:078] | Nextion is not connected!
20:05:20 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:05:20 | [W] | [nextion:078] | Nextion is not connected!
20:05:21 | [W] | [nextion:078] | Nextion is not connected!
20:05:21 | [E] | [uart:015] | Reading from UART timed out at byte 0!
20:05:21 | [W] | [nextion:078] | Nextion is not connected!
20:05:22 | [W] | [nextion:078] | Nextion is not connected!
```
 
Interspersed with regular reports from the ESP about temperature etc.
What can I do to investigate this problem? 

Kind regards,
Jelle

**Comment by Jelle-Tigchelaar** [comment] 2022-12-13 20:44
I have fixed the screen connection issue by chang the baud rate to 9600:

`
##### UART FOR NEXTION DISPLAY #####
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600 #115200
  id: tf_uart
`

that's line `107`. But now i'm faced with other issues:

`ERROR: Received string return but next in queue "set_component_text" is not a text sensor`

And a broken UI as a consequence. None of the settings I made in the blueprint show up, changing the temp offset does work, so it's communicating...
What should my next steps be?

**Comment by joaomruas** [comment] 2022-12-13 21:58
Same problem
Just Flashed out of the box ESP panel and flashed TFT.
Nextion is not connected!
Changed baud rate, same error ( ERROR: Received string return but next in queue "set_component_text" is not a text sensor)

**Comment by Blackymas** [comment] 2022-12-14 07:51
pls share esphome code and blueprint yaml code and also the trace after reboot nspanel.

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo-%7C-Alle-wichtigen-Dinge-die-man-wissen-sollte#1-wie-erstelle-ich-issues-wenn-ich-ein-problem-habe

not sure what problem do you have, because a lot of nspanel are flashed witch my version

**Comment by Blackymas** [comment] 2022-12-14 08:21
if you do not use accuweather, the default ha weather is used.

Do a reboot of the nspanel and then go to the automation and traces - maybe there is something hanging somewhere. 

this is the first branch like in the wiki picture

**Comment by Jelle-Tigchelaar** [comment] 2022-12-14 12:41
A little update on the experience so far.
I have switches to AccuWeather, this works fine, I was using OpenWeather before, which I assume isn't what's referred to as default weather, but I could find no mention of the default weather in the docs.

The climate is working now, so that is excellent.

I will focus on adding some devices to the other screens and hopefully the good stuff will keep coming.

Still on the 9600 baud, I'm thinking of changing it back to 115200, but al little afraid because it's finally working...

**Comment by joaomruas** [comment] 2022-12-14 18:42
Is the "set_component_text" Weather related?

I don't think the issue is only weather related as I can't configure the panel. (no climate no buttons etc.)
And Jelle-Tigchelaar also experienced this inability to configure.

I'm updating my home assistant instance as this issue seems to affect only two users. (something needs to be different on my end ) (not considering hardware revisions)
Home Assistant 2022.9.6
Supervisor 2022.11.2
Operating System 9.0
Interface: 20220907.2 - latest

Later I'll procede with "automation and traces" and other debugging.

Blueprint and Yaml are minimal. (only baud rate altered)

**Comment by Guy-Falkes** [comment] 2022-12-15 00:29
I'm having the exact same issue here, not an advanced user though so i just followed the simple steps and keep getting the following message in the logs:
[01:28:29][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:29][W][nextion:078]: Nextion is not connected! 
[01:28:29][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:29][W][nextion:078]: Nextion is not connected! 
[01:28:30][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:30][W][nextion:078]: Nextion is not connected! 
[01:28:30][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:30][W][nextion:078]: Nextion is not connected! 
[01:28:31][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:31][W][nextion:078]: Nextion is not connected! 
[01:28:32][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:32][W][nextion:078]: Nextion is not connected! 
[01:28:32][E][uart:015]: Reading from UART timed out at byte 0!
[01:28:32][W][nextion:078]: Nextion is not connected! 
[01:28:33][E][uart:015]: Reading from UART timed out at byte 0!

**Comment by joaomruas** [comment] 2022-12-15 12:49
Hi @Guy-Falkes.

I woud think that a diffrent Nextion screen is beeing used.  (?) @Blackymas 

Either way, the way we changed the baud rate is to manualy change the YAML;
This is done by importing [nspanel_esphome.yaml] from this repo into the ESP home (edit) code. (copy paste)

replacing what is inside the 
"##### DO NOT CHANGE ANYTHING! #####" brackets.
(keeping the substitutions before)

And then changing line 107: (from 115200 to 9600) 
"uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600 
  id: tf_uart
"

If you fell confortable either change this or wait for a new solution if the problem is indeed on hardware level...

**Comment by deejaybeam** [comment] 2022-12-15 13:29
maybe this is a setting in the nextion display (TFT)-File see: https://nextion.tech/instruction-set/
```
baud=9600, bauds=9600
--
Sets the Nextion Baud rate in bits-per-secondmin 2400, max 921600, default 9600 or user definedValid values are: 2400, 4800, 9600, 19200, 31250, 38400, 57600, and 115200, 230400, 250000, 256000, 512000, and 921600Note: baud=38400 will set the current baud rate to 38400using bauds=38400 will set the current baud rate to 38400 and save this to be new power on default baud rate, persisting until changed.Note: on rare occasions bauds has become lost. With the addition of the Editor Program.s feature, it is now recommended to specify your desired baud rate baud=9600 between declarations and before the page0 instruction and no longer recommending inserting bauds=9600 in the first page’s Preinitialization Event of the HMI.

```
So maybe it makes sense to add this to the program.s inside HMI/TFT

**Comment by deejaybeam** [comment] 2022-12-15 13:34
Also recommended here:
https://esphome.io/components/display/nextion.html

**Comment by joaomruas** [comment] 2022-12-15 14:08
Makes Sense, 
I'm not setup for this type of development yet (HMI/TFT).
This seems easy, but why would'nt it affect all users?
 For me, at boot i will try to open at 9600 and "baud" command to change to 115200 (not "bauds" just in case...)

**Comment by Guy-Falkes** [comment] 2022-12-15 23:11
> baud_rate: 9600

That did the trick.... Thanks. I now have a working NSPanel to play with.

**Comment by pepe59** [comment] 2022-12-16 20:25
After playing the tft file the screen ended in System Data ERROR!
I tried uploading a blank tft but the screen flashes 2x and the error is still there. Will something be done about it or did I just destroy nspanel.
Thank you

**Comment by pepe59** [comment] 2022-12-17 11:05
Solved. The url configuration entered directly into the display settings. Uploaded an empty tft file, then  a simple project just to display temperatures. Everything went well and the display is working as it should again.

**Comment by jirimissbach** [comment] 2022-12-27 17:01
Hello, I just got a brand new panel, and I'm facing the same issue as discussed here. I did clone the repo and changed line 107 baud rate to 9600, but I still can't get the display to work correctly. There are no errors until I trigger the "Update TFT display". 

 I can see that the config changes are in place

`
[17:59:39][C][logger:293]: Logger:
[17:59:39][C][logger:294]:   Level: DEBUG
[17:59:39][C][logger:295]:   Log Baud Rate: 115200
[17:59:39][C][logger:296]:   Hardware UART: UART0
[17:59:39][C][uart.arduino_esp32:108]: UART Bus 1:
[17:59:39][C][uart.arduino_esp32:109]:   TX Pin: GPIO16
[17:59:39][C][uart.arduino_esp32:110]:   RX Pin: GPIO17
[17:59:39][C][uart.arduino_esp32:112]:   RX Buffer Size: 256
[17:59:39][C][uart.arduino_esp32:114]:   Baud Rate: 9600 baud
[17:59:39][C][uart.arduino_esp32:115]:   Data Bits: 8
[17:59:39][C][uart.arduino_esp32:116]:   Parity: NONE
[17:59:39][C][uart.arduino_esp32:117]:   Stop bits: 1
`

more logs


`
[17:44:45][D][switch:013]: 'Update TFT display' Turning ON.
[17:44:45][D][nextion_upload:169]: Connected
[17:44:45][D][nextion_upload:175]: Requesting URL: https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft
[17:44:47][D][nextion_upload:209]: Updating Nextion NX4832F035_011C...
[17:44:47][D][nextion_upload:235]: Waiting for upgrade response
[17:44:47][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:47][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:47][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:47][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:47][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:48][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:49][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:49][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:49][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:49][E][uart:015]: Reading from UART timed out at byte 0!
[17:44:49][D][nextion_upload:239]: Upgrade response is  19
[17:44:49][D][nextion_upload:242]: Available 0 : 0x00
[17:44:49][D][nextion_upload:242]: Available 1 : 0x00
[17:44:49][D][nextion_upload:242]: Available 2 : 0x00
[17:44:49][D][nextion_upload:242]: Available 3 : 0x00
[17:44:49][D][nextion_upload:242]: Available 4 : 0x00
[17:44:49][D][nextion_upload:242]: Available 5 : 0x00
[17:44:49][D][nextion_upload:242]: Available 6 : 0x00
[17:44:49][D][nextion_upload:242]: Available 7 : 0x00
[17:44:49][D][nextion_upload:242]: Available 8 : 0x00
[17:44:49][D][nextion_upload:242]: Available 9 : 0x00
[17:44:49][D][nextion_upload:242]: Available 10 : 0x00
[17:44:49][D][nextion_upload:242]: Available 11 : 0x00
[17:44:49][D][nextion_upload:242]: Available 12 : 0x00
[17:44:49][D][nextion_upload:242]: Available 13 : 0x00
[17:44:49][D][nextion_upload:242]: Available 14 : 0x00
[17:44:49][D][nextion_upload:242]: Available 15 : 0x00
[17:44:49][D][nextion_upload:242]: Available 16 : 0x00
[17:44:49][D][nextion_upload:242]: Available 17 : 0x00
[17:44:49][D][nextion_upload:242]: Available 18 : 0x00
[17:44:49][D][nextion_upload:248]: preparation for tft update failed 0 ""
[17:44:49][D][nextion_upload:324]: Restarting Nextion
[17:44:51][D][nextion_upload:327]: Restarting esphome
INFO nspanel1.local: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO nspanel1.local: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for nspanel1.local
WARNING Disconnected from API
INFO Successfully connected to nspanel1.local
[17:45:01][D][api:102]: Accepted ::FFFF:10.0.0.36
[17:45:01][D][api.connection:918]: Home Assistant 2022.12.8 (::FFFF:10.0.0.36): Connected successfully
[17:45:01][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:01][W][nextion:078]: Nextion is not connected! 
[17:45:01][D][api:102]: Accepted ::FFFF:10.0.0.60
[17:45:01][D][api.connection:918]: ESPHome Logs 2022.12.3 (::FFFF:10.0.0.60): Connected successfully
[17:45:02][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:02][W][nextion:078]: Nextion is not connected! 
[17:45:03][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:03][W][nextion:078]: Nextion is not connected! 
[17:45:03][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:03][W][nextion:078]: Nextion is not connected! 
[17:45:04][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:04][W][nextion:078]: Nextion is not connected! 
[17:45:05][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:05][W][nextion:078]: Nextion is not connected! 
[17:45:05][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:05][W][nextion:078]: Nextion is not connected! 
[17:45:06][E][uart:015]: Reading from UART timed out at byte 0!
[17:45:06][W][nextion:078]: Nextion is not connected! 
`

**Comment by markeff** [comment] 2022-12-27 22:06
Same problem here. Flashing seemed to go fine but same errors as others when it comes to update the TFT display.

**Comment by jdickensttu** [comment] 2022-12-28 02:49
I had the same issue (Nextion is not connected!, Reading from UART timed out at byte 0!).  I can reproduce the fix as well as the corruption.  To fix I use Jelle-Tigchelaar's branched version with 9600 baud to the panel along with a local copy of the blank nspanel.tft file placed in the www directory (\config\www) on the pi (see below)

#nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
nextion_update_url: http://homeassistant.local:8123/local/nspanel_blank.tft     
#url: https://github.com/Blackymas/NSPanel_HA_Blueprint
url: https://github.com/Jelle-Tigchelaar/NSPanel_HA_Blueprint

After uploading the firmware with these changes, send the upload TFT command ("ESPHome: DEVICE_NAME_upload_tft").  This will load the blank nspanel.tft.
Once the blank nspanel.tft is loaded, change the code back to the original:

nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
#nextion_update_url: http://homeassistant.local:8123/local/nspanel_blank.tft     
url: https://github.com/Blackymas/NSPanel_HA_Blueprint
#url: https://github.com/Jelle-Tigchelaar/NSPanel_HA_Blueprint

Once the firmware is uploaded, send the upload TFT command again.  This will flash display with Blackymas' panel and it should be working.

I can reproduce the same error by attempting to upload a new TFT file, while an existing write is in progress or if a write is interrupted for any reason (power, network, etc).  To recover, I have to perform the above steps each time.

I am more careful when uploading new TFT files now and have not had the issue with over 50 writes.

**Comment by deejaybeam** [comment] 2022-12-31 08:35
Had the same problem yesterday with my latest panel. What I have done to solve the problem is:
1. Set ```baud_rate: 9600``` in the esphome-file and flash it
2. Upload a tft-file where ```baud=115200``` in program.s
3. Set ```baud_rate: 115200``` back to original-value in the esphome-file and flash it.

The installation of the tft with 115200 tooks very long, because of the low baud-setting and the new tft with support for all the required charakters to support the new languages has a size of 8MB.

**Comment by Levanterman** [comment] 2023-01-01 20:33
I had the same issues with a few NSPANELs. The baud rate error and also the screen might display a SYSTEM ERROR on a blank Nextion. 

To fix it, i just updated the firmware with this via ESP Home (similar process) :
[https://github.com/marcfager/nspanel-mf](url)
(optional : but you can change the URL in this link to the Blank ns panel TFT to speed it up). 

and then re-do the firmware again with this Blackymas's version 

This fixed the baud rate and the screen error. I am note sure its a delta in the Hardware, it all works perfectly once the firmware is totally removed and flashed again and the screen issue disappeared.

**Comment by markeff** [comment] 2023-01-01 21:12
I had the system data error issue as well but couldn’t seem to resolve it by reflashing following Marc Fager. Instead, I flashed it with Tasmota and got it all working again and will retry with the Blackymass version from here.

**Comment by rploeg** [comment] 2023-01-14 10:44
I have tried @jdickensttu solution, but stock on the same errors in the logs (UART etc). Also see on the System Date Error onmy panel screen. 

I have tried it with three new panels with all the same errors. I use Marc Jager his solution to flash the device, but that didn't worked and hitting the same errors as the rest in this threat. Flashing looks successful, but TFT update don't.   

So, I tried with one panel (after the above errors) the marc jager full deployment (also his yaml code ) and that works directly and can interact with the screens. So can confirm that the panels are working. 

Any ideas what I can do to solve this error?

**Comment by Blackymas** [comment] 2023-01-16 22:21
@rploeg 
have you check https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166 and https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/177

**Comment by Blackymas** [comment] 2023-01-18 23:24
I close the issue because we discuss the topic in #166

**Closed by Blackymas** 2023-01-18 23:24 UTC
Labels: problem, question

**Comment by jshep321** [comment] 2023-03-08 17:45
Hey,
I had some issues with this solution.  I made my own blank and US tft's with the nextion editor for my board (US) from the HMI files.  Are the included files for NX4832F035_011C ?  Using this in the Device with 180 vertical worked for me.  Curious if the blank is intended to work with US version?  Seems very landscape to me. :)
