### ISSUE TITLE
Climate Control Questions

### ISSUE THREAD

**Issue by JS1Dev** [Blackymas/NSPanel_HA_Blueprint#1418] opened 2023-12-14 04:00 UTC
Hi all, I'm looking for help on the Climate control

1. **Why can't I see the new climate add-on in my NSPanel?**
Probably the easiest - I seem to be missing a step to see the new [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) on my panel as it doesn't display
- I just see the initial weather page and the 4 other pages (the first one has multiple buttons most of which work as expected - more on that to follow in extra credit :)
- In my Blueprint automation, under "CLIMATE", the Climate to Control - ENTITY is my climate.nsplivingroom_thermostat entity is selected from the dropdown
- My Nsplivingroom ESPHome device shows Thermostat (under Controls) and when I click on it I see the circular amber slider with Mode and Preset (also see below image)
- I did a Restart Home Assistant and unplugged and plugged back in the NSPanel
- The following are specified in my .yaml file which I successfully installed - btw the refresh is 300s like in the [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) example (it was 1s, is 300s a lot)?
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/c7b25660-3fd3-472c-9d6b-dd2947517749)

2. **Why does it's seem to be setup for Celsius where I think Fahrenheit is configured?**
- My configuration.yaml has unit_system: imperial and temperature_unit: F under homeassistant: - and the NSPanel home screen correctly reflects Fahrenheit values also showing "F" for Fahrenheit (both in and out doors)
- I got the following compile error if I used 40 and 80 for min/max temps so I set them to the Celsius equivalents of 4.44 and 26.66 to get by that compile error but it still shows in HA as Celsius value with the Fahrenheit symbol: "Error: default_target_temperature_low for Home is set to -6.111111111111112 which is less than the visual minimum temperature of 4.444444444444445"
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/7168cc24-351f-44b8-936e-57456a1f28aa)

3. **Will it support Generic Thermostat settings?**
Will I be able to set all these options from [Generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) using the new [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate)?
- away_temp float (optional)
- comfort_temp float (optional)
- home_temp float (optional)
- sleep_temp float (optional)
- activity_temp float (optional)

4. **Can I use a different climate thermostat?**
I may be interested in using [Awesome Thermostat](https://community.home-assistant.io/t/an-awesome-thermostat/469391) along with the [Scheduler Component](https://github.com/nielsfaber/scheduler-component) if this thermostat doesn't pan out
- Should I be able to just put the climate entity from this other thermostat and have it show on the NSPanel by updating my Blueprint automation, under "CLIMATE", the Climate to Control - ENTITY with the climate entity?
- Any reason why I shouldn't be able to use the [Scheduler Component](https://github.com/nielsfaber/scheduler-component) with the new [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate)?

EXTRA CREDIT :)
5. Why do the following 2 entities not work on my button page, are they not supported (they work fine in HA)?
- remote.living_room - turns on my TV
- group.daily_outside_lights - a group entity I created in my configuration.yaml to turn multiple lights on/off

6. Can I have a button that has a toggle switch on it that works similar to light entities have white (on) button and light black (off) buttons?

**Comment by edwardtfn** [comment] 2023-12-15 13:48
> 1. Why can't I see the new climate add-on in my NSPanel?

Your ESPHome settings looks all right, however you still have to select that new entity as your climate entity in your blueprint settings. Have you done that?

**Comment by edwardtfn** [comment] 2023-12-15 13:49
> 2. Why does it's seem to be setup for Celsius where I think Fahrenheit is configured?

I will try to duplicate that and come back to you.

**Comment by edwardtfn** [comment] 2023-12-15 13:53
> 3. Will it support Generic Thermostat settings?
> 4. Can I use a different climate thermostat?
> I may be interested in using [Awesome Thermostat](https://community.home-assistant.io/t/an-awesome-thermostat/469391) along with the [Scheduler Component](https://github.com/nielsfaber/scheduler-component) if this thermostat doesn't pan out

The add-on climate will enable the thermostat fully controlled by your panel locally, however, if you wanna use some other thermostat integration from Home Assistant that still possible.
In this case, don't use the add-on climate and instead set the generic/awesome thermostat using the entities related to your panel's thermometer and relay. That will create a new climate entity in Home Assistant which can be assigned to your panel on the Blueprint settings.

**Comment by edwardtfn** [comment] 2023-12-15 13:57
> 5. Why do the following 2 entities not work on my button page, are they not supported (they work fine in HA)?
>
>remote.living_room - turns on my TV
>group.daily_outside_lights - a group entity I created in my configuration.yaml to turn multiple lights on/off

I think remote is not supported, but I don't see anything preventing this. Why don't you create a feature request for this? I will be happy to investigate it.
About groups, the old group entity isn't supported, but you can create a "light group" which will have similar results, but instead will create an entity named "light.daily_outside_lights" and that would be supported.

**Comment by edwardtfn** [comment] 2023-12-15 14:01
> 6. Can I have a button that has a toggle switch on it that works similar to light entities have white (on) button and light black (off) buttons?

Isn't working like this already?

**Comment by edwardtfn** [comment] 2023-12-18 02:00
Still something pending here or can we close this issue?

**Comment by JS1Dev** [comment] 2023-12-18 02:14
Thanks so much @edwardtfn 

**Complete**
- 1 - I didn't realize how to access the thermostat from the panel, for some reason I was thinking it was going to take up one of the other 4 pages, I was pleasantly surprised that wasn't the case and that you just click on the temperature
- 3 (and 4) - because of # 2 (below) I am using using  but am hoping to use the add-on instead along with the climate custom presets
- 5 - Thanks, I created the following enhancement request: [Enhancement - Support for Entity: remote #1434](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1434)

**Remaining questions:**
2. That would be great if you could duplicate the Celsius vs Fahrenheit issue I described.  The climate custom presets are configured in configuration.yaml, correct?
6. Thanks for the tip for replacing my old group with the new group - the new one works and I like it better because the bulb turns off/on.  I had it as group because I have 2 other groups where I couldn't use the new light group because it also includes entities of type switch so the new light group logs an error saying switch isn't allowed

**New question:**
7. My blueprint used to have a button entity with id: switch.plug12 which just turned on a light.  I've switched that to the entity id: tasmota_furnaceheatlivingroom1 (which is on a Sonoff 4ch pro I have directly connected to my furnace and works as expected from HA), but it seems to still somehow only be interacting with the switch.plug12 (when I raise and lower the temperature in both the panel and the temperature card in HA)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/2fc60a90-b285-4d66-a11d-2be37bf5b19e)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/bd21e8eb-7711-425e-9190-7aafe35cd57e)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/cb552a94-09cc-469c-91d8-1f42954535f2)

**Comment by edwardtfn** [comment] 2023-12-18 02:36
> 2. That would be great if you could duplicate the Celsius vs Fahrenheit issue I described. The climate custom presets are configured in configuration.yaml, correct?

 It should be on the same yaml file where you set your panel, in the substitutions area, close to where is the panel name, url for tft file, etc.

In your case, I believe it is named `nsplivingroom.yaml':
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/c7b25660-3fd3-472c-9d6b-dd2947517749)

But you should also provide the max an min supported temperatures in Fahrenheit, as that will be limiting the range your thermostat will support.

**Comment by edwardtfn** [comment] 2023-12-18 02:38
> 6. Thanks for the tip for replacing my old group with the new group - the new one works and I like it better because the bulb turns off/on. I had it as group because I have 2 other groups where I couldn't use the new light group because it also includes entities of type switch so the new light group logs an error saying switch isn't allowed

You can also create an light entity from your switch, and then use that light entity in your group.
You will find all those functionalities under Settings > Devices & Services and then the tab "Helpers".

**Comment by edwardtfn** [comment] 2023-12-18 02:40
> 7. My blueprint used to have a button entity with id: switch.plug12 which just turned on a light. I've switched that to the entity id: tasmota_furnaceheatlivingroom1 (which is on a Sonoff 4ch pro I have directly connected to my furnace and works as expected from HA), but it seems to still somehow only be interacting with the switch.plug12 (when I raise and lower the temperature in both the panel and the temperature card in HA)

You are mixing the custom buttons. There are custom buttons on the Home page and custom buttons on the Climate page. Those are configured in different areas in your blueprint settings and will be recorded in different fields as it is visible in the yaml you shared.

**Comment by JS1Dev** [comment] 2023-12-18 03:23
> > 2. That would be great if you could duplicate the Celsius vs Fahrenheit issue I described. The climate custom presets are configured in configuration.yaml, correct?
> 
> It should be on the same yaml file where you set your panel, in the substitutions area, close to where is the panel name, url for tft file, etc.
> 
> In your case, I believe it is named `nsplivingroom.yaml': ![image](https://private-user-images.githubusercontent.com/148407073/290390438-c7b25660-3fd3-472c-9d6b-dd2947517749.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjczMTksIm5iZiI6MTcwMjg2NzAxOSwicGF0aCI6Ii8xNDg0MDcwNzMvMjkwMzkwNDM4LWM3YjI1NjYwLTNmZDMtNDcyYy05ZDZiLWRkMjk0NzUxNzc0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwMjM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjM4ZTA5MjE5OTA3ZmM4ODA3NGEyMmJhMDYzMmE0YmUyYmZhMDk4ZWNjM2VhODBjMDg2MzU0NjlhMzNmMDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zEqbbDLTrZLv90LjAbiVWkfex-hSHTQRSBJTlQ0Fh98)
> 
> But you should also provide the max an min supported temperatures in Fahrenheit, as that will be limiting the range your thermostat will support.

Got it, nsplivingroom.yaml, thanks!  But I can't provide the max and min supported temperatures in Fahrenheit, that's the issue I mentioned in # 2 (below) that you mentioned you'd try to reproduce
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/964f943e-08ea-4211-9515-f2e4cd03cbaf)

**Comment by JS1Dev** [comment] 2023-12-18 03:38
> > 7. My blueprint used to have a button entity with id: switch.plug12 which just turned on a light. I've switched that to the entity id: tasmota_furnaceheatlivingroom1 (which is on a Sonoff 4ch pro I have directly connected to my furnace and works as expected from HA), but it seems to still somehow only be interacting with the switch.plug12 (when I raise and lower the temperature in both the panel and the temperature card in HA)
> 
> You are mixing the custom buttons. There are custom buttons on the Home page and custom buttons on the Climate page. Those are configured in different areas in your blueprint settings and will be recorded in different fields as it is visible in the yaml you shared.

Actually, from the images of the Blueprint and the automations.yaml that the blueprint updates that I sent, unless I'm missing something it looks like I'm appropriately updating the entity for the Climate page (not the custom buttons) which I _think_ is reflected in the application.yaml showing it as **climate_button08**: switch.tasmota_furnaceheatlivingroom1.  Definitely apologize I'm probably missing something obvious - maybe you could send a screenshot of where I should be specifying in the the Blueprint vs where my image shows it currently?

**Comment by edwardtfn** [comment] 2023-12-18 04:52
> But I can't provide the max and min supported temperatures in Fahrenheit, that's the issue I mentioned in # 2 (below) that you mentioned you'd try to reproduce

Sorry, it was too late here and I was probably sleeping when I missed that one. 😂

**Comment by edwardtfn** [comment] 2023-12-18 04:54
I believe the problem is the fact the internal sensor always provides Celsius. I will try to find a way to change it.

**Comment by edwardtfn** [comment] 2023-12-18 11:43
So, I couldn't replicate the issue.

Could you please share your `nsplivingroom.yaml` (please remove sensitive info) with the values in Fahrenheit (20 and 80?) and the log of the compiling error?

**Comment by edwardtfn** [comment] 2023-12-18 22:19
Ok, for item 2 I think I could duplicate the issue. There is a hard coded target temperature which can be out of your range if you select Fahrenheit.
I'm working on a fix for v4.2, changing this to a substitution, but meanwhile, please try adding this to your customization area:

```yaml
climate:
  - id: !extend thermostat_embedded
    preset:
      - name: "Off"
        default_target_temperature_low: 65 °F
        mode: "off"
      - name: Home
        default_target_temperature_low: 65 °F
        mode: "heat"
```

Don't worry about the value "65". It just have to be something inside your selected range (20 to 80?). This will be the initial target, but you will be able to change on HA or even on your panel when it is running.

**Comment by edwardtfn** [comment] 2023-12-20 08:53
Fixed on `dev`.

**Comment by JS1Dev** [comment] 2023-12-21 05:25
> Ok, for item 2 I think I could duplicate the issue. There is a hard coded target temperature which can be out of your range if you select Fahrenheit. I'm working on a fix for v4.2, changing this to a substitution, but meanwhile, please try adding this to your customization area:
> 
> ```yaml
> climate:
>   - id: !extend thermostat_embedded
>     preset:
>       - name: "Off"
>         default_target_temperature_low: 65 °F
>         mode: "off"
>       - name: Home
>         default_target_temperature_low: 65 °F
>         mode: "heat"
> ```
> 
> Don't worry about the value "65". It just have to be something inside your selected range (20 to 80?). This will be the initial target, but you will be able to change on HA or even on your panel when it is running.

Hi @edwardtfn, I setup up a 2nd NSPanel for my kitchen and am using the [Add‐on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) for that one (leaving my Livingroom alone still using [Awesome Thermostat](https://community.home-assistant.io/t/an-awesome-thermostat/469391)) and have made the changes you suggested but I'm not sure what the impact should be as I'm still stuck with the Celsius min/max (as shown below).

That said, it looks like you've fixed this, and it sounds like it'll be part of v4.2?  If so, is there a general timeframe for that release?
- As a side, back before using ESPHome w/ this Blueprint, I had my old panel working w/ Tasmota and had the same problem which I was able to work around with a solution I had posted in [NSPanel Lovelace UI - Show Fahrenheit Instead of Celsius](https://community.home-assistant.io/t/nspanel-lovelace-ui-show-fahrenheit-instead-of-celsius/504413)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/10fd1206-0912-407f-bd0e-b04d26f5d348)

**Comment by edwardtfn** [comment] 2023-12-21 05:40
> That said, it looks like you've fixed this, and it sounds like it'll be part of v4.2? If so, is there a general timeframe for that release?

That's right, I believe this is fixed on v4.2, which is in `dev` now.
My original goal was to release it no later than January 3rd: https://github.com/Blackymas/NSPanel_HA_Blueprint/milestone/2
Usually I target the first Wednesday in a month, aligned with Home Assistant release and I use their beta phase to double check if something is breaking so I can come with a fix on the last minute.
Anyways, I usually release earlier than that, but as still work to do, I'm not gonna make any promises here. 😉 

But I can look in a way to implement it as a customization, so you can use it now and give me some feedback.

Give me a few minutes.

**Comment by edwardtfn** [comment] 2023-12-21 05:52
By the way, you will make my life easier if you share your code as text, and not pictures. 😉 

Please try this:
```yaml
climate:
  - id: !extend thermostat_embedded
    on_boot_restore_from: memory
    default_preset: eco
    preset:
      - name: eco
        default_target_temperature_low: 65 °F
        mode: "heat"
      - name: away
        default_target_temperature_low: 55 °F
        mode: "heat"
      - name: boost
        default_target_temperature_low: 64 °F
        mode: "heat"
      - name: comfort
        default_target_temperature_low: 65 °F
        mode: "heat"
      - name: sleep
        default_target_temperature_low: 55 °F
        mode: "heat"
    visual:
      min_temperature: 40 °F
      max_temperature: 80 °F
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1

sensor:
  - id: !extend temp_nspanel
    unit_of_measurement: "°F"
    filters:
      - lambda: |-
          return (x * (9.0/5.0)) + 32.0 + temperature_correction->state;
```

**Comment by edwardtfn** [comment] 2023-12-21 05:55
Please let me know your results. 😃

**Comment by JS1Dev** [comment] 2023-12-21 06:21
Hey, thanks for giving it a shot, but I ran into this error.  btw, it's about 1:20am for me here (this is the time I get to play with this stuff lol!), but have have to get up for work tomorrow though I'll give any other suggestions you might have a shot tomorrow 😃

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/44f15b8d-8f57-4826-bd67-4ffe2878390f)

**Comment by edwardtfn** [comment] 2023-12-21 07:17
> Hey, thanks for giving it a shot, but I ran into this error. 

Could you please share the error logs?

**Comment by JS1Dev** [comment] 2023-12-22 00:33
The install log just reflects the same error as I posted in the edit interface (^^^) but for ref, I added it below
- I actually am super appreciative that you fixed this and am more to happy to wait for when it's released, unless of course, you're interested in pursuing this approach, in which case I'm also happy to try anything you'd like

One quick side question though, [(EN) Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) states the following, but if network availability goes out you have no access to the thermostat and you essentially lose your thermostat functionality, correct?  If so, that would be one downside to using the NSPanel as a thermostat.  If not, how can it be used if network availability goes out?
- "This add-on enables the use of your panel's relays to act as a thermostat (either cooler or heater) using the internal temperature sensor and independent of the network availability."

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/a42b8fcb-dbde-4196-ad3c-af427f7b4150)

**Comment by edwardtfn** [comment] 2023-12-22 20:33
Could you please share here the content of your file `nsplivingroom.yaml`? Not a screenshot, but the text of the file. Just copy from there and paste here, then remove any sensitive information (Wi-Fi passwords, etc).

**Comment by JS1Dev** [comment] 2023-12-23 20:49
Hi @edwardtfn, I've actually switched it to my nspkitchen.yaml.  Here's the text for both the .yaml as well as the text from the log

[YamlAndLog.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13760198/YamlAndLog.txt)

**Comment by edwardtfn** [comment] 2023-12-23 23:33
I see you've commented out the relay settings.
```yaml
  #heater_relay: "1" #Use relay 1
```
Which relay do you have your heater wired to?

**Comment by edwardtfn** [comment] 2023-12-23 23:42
I found the error in the code that will prevent it to work with "F".
It's already fixed in `DEV`, but I will take a deeper look later.

**Comment by edwardtfn** [comment] 2023-12-23 23:43
But back to my previous question, if you don't set one of the relays (and wire your heater there), the add-on is useless. 😉

**Comment by JS1Dev** [comment] 2023-12-24 17:35
> But back to my previous question, if you don't set one of the relays (and wire your heater there), the add-on is useless. 😉

Good question :).  Instead of the relay, I use wifi switches ([Sonoff 4 ch](https://sonoff.tech/product/diy-smart-switches/4chr3-4chpror3/)) that are wired directly into my HVAC controller board and work the same way my thermostat does where when the temperature reaches a certain point it triggers the furnace (depending on the mode (heat/AC/fan)).  I'm not sure it's the best way to do what I want but I'm doing this currently with the [Awesome Thermostat](https://community.home-assistant.io/t/an-awesome-thermostat/469391) along with the [Scheduler Component](https://github.com/nielsfaber/scheduler-component), and so far (I've just hooked up 1 zone to 1 of my 3 thermostats (NSPanels)), and it's really worked well as a smart thermostat (+ switch control panel).  The one downside of this approach from conventional thermostats is that in addition to electricity, it has a 2nd point of failure, which is wifi/network as my switches are all wifi though in my case that's pretty solid/reliable.

**Comment by edwardtfn** [comment] 2023-12-24 22:58
The add-on climate will only control the local physical relays. Either the relay 1k the relay 2 or a dummy relay 0. That will not control a remote device that is not wired to your panel.
You can still use your panel to control your remote device, but then in that case you don't need to install the add-on and all the presets, etc will be set in the other integration (or awesome thermostat, generic thermostat, etc), but you control the target temperature, activate the different modes, etc, from your panel. Just associate the climate entity from your thermostat to any of the buttons or to the main climate on the Blueprint settings. No need to fo anything in ESPHome yaml.

That will be using the wifi, that's true. But if you wanna avoid that dependancy, the only way is to hard wite the thermostat controller to your panel. Then you install the add-on and will be able to fully local control. 😉

**Comment by JS1Dev** [comment] 2023-12-26 20:35
Hi @edwardtfn, so I setup the [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) and all my config is via my esphome .yaml (nspkitchen.yaml in my case) using Celsius just to test for now until the fix for "F" Fahrenheit is available, and I see that there is no network dependency - I love it!
- I assume this is because it's all ESPHome configuration in my nspkitchen.yaml which I install directly to the NSPanel, correct?

**Enhancement or is this already possible?**
- Instead of an amount of time determining when the thermostat will turn on/off (using min_off_time and min_run_time of [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate)), is there a way to set a hot_tolerance & cold_tolerance (see [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/)) where if the target temperature is 25 and the hot_tolerance is 0.5 the heater will stop when the sensor equals or goes above 25.5?

**Using the relays**
- Is the power from the relay isolated from the 5V & GND on the NSPanel board (see below image or also [blakadder's teardown](https://blakadder.com/nspanel-teardown/))?

If so, I _think_ I can solve the problem of my furnace requiring 24V by powering the NSPanel with 5V to support the NSPanel and powering the relays with 24V as described below

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/148407073/313e36c9-d234-447e-b4f9-b1a6a51ac9c3)

**Comment by edwardtfn** [comment] 2023-12-28 01:37
I have no idea if that will work as I've never tested anything similar to this. 😆 
But I think you have a good chance. But I believe the furnace is 24VDC, is that correct?
There is the original power circuit on the relay board which will convert 110VAC/220VAC to 5VDC. That circuit will still be there when you power it with 24VDC and I'm not sure how that would be with your panel powered by a different 5VDC circuit.
You may find some info about this on that teardown page.

**Comment by JS1Dev** [comment] 2023-12-28 04:25
Hi @edwardtfn, I tested it today, it worked like a charm :).  I did update my image with one change that represents what worked for me when I tested for heat.

3 QUESTIONS (now that I'm this far 😆:

From [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) I see the following:

"At this moment you have to choose between heat or cool. The dual/simultaneous operation is not supported at this moment."
1. Will the dual/simultaneous operation be supported in the next release with the Fahrenheit fix?

"A target temperature must be set on the climate entity in Home Assistant or the page Climate in your panel."

2. This is represented by "default_target_temperature_low" in the climate section of my esphome (nspkitchen.yaml), correct?

In testing, I noticed that when I set "min_off_time" and "min_run_time" (see [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate)) each to 1 second, when the temperature goes .5 degree Celsius below the target temperature it triggers the relay ON (after a second), and when the temperature goes .5 degrees Celsius over the target temperature, it triggers the relay OFF (after a second).

3. Is there an [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) setting that I can configure to determine this .5 degree Celsius differential (i.e. "hot_tolerance" as described in [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/))?  Same question regarding setting the "cold tolerance"?

**Comment by edwardtfn** [comment] 2023-12-28 08:35
> 1. Will the dual/simultaneous operation be supported in the next release with the Fahrenheit fix?

Yes.

> "A target temperature must be set on the climate entity in Home Assistant or the page Climate in your panel."

> 2. This is represented by "default_target_temperature_low" in the climate section of my esphome (nspkitchen.yaml), correct?

Correct, but that is set when you adjust the target temperature using the panel's slider or using a climate card into Home Assistant. You also have the presets.

> In testing, I noticed that when I set "min_off_time" and "min_run_time" (see [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate)) each to 1 second, when the temperature goes .5 degree Celsius below the target temperature it triggers the relay ON (after a second), and when the temperature goes .5 degrees Celsius over the target temperature, it triggers the relay OFF (after a second).

> 3. Is there an [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Add%E2%80%90on:-Climate) setting that I can configure to determine this .5 degree Celsius differential (i.e. "hot_tolerance" as described in [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/))? Same question regarding setting the "cold tolerance"?

I believe so. If I understood your question, this is the dead band/hysteresis: https://esphome.io/components/climate/thermostat.html#controller-behavior-and-hysteresis
You can use any of the settings from that controller by just adding to that `!extend` as you used before.

**Comment by edwardtfn** [comment] 2023-12-28 08:53
I will close this to remove from the pending list for v4.2, but please feel free to continue the discussion or to open a new issue if you face something else.

**Closed by edwardtfn** 2023-12-28 08:53 UTC
Labels: Bug, Question, Customization, Page: climate

**Comment by JS1Dev** [comment] 2023-12-28 23:27
Thanks for the deadband setting reference, I'm not sure how I missed that when I was on the [Thermostat Climate Controller](https://esphome.io/components/climate/thermostat.html#controller-behavior-and-hysteresis) page...  😆

Thanks so much @edwardtfn for all the help with all my questions!  I'm really looking forward to the 4.2 release!  Have a wonderful New Years!
