### ISSUE TITLE
`BUG` Compiling not possible - help needed

### ISSUE THREAD

**Issue by Uli1900** [Blackymas/NSPanel_HA_Blueprint#1650] opened 2024-01-16 14:46 UTC
### ESPHome Version

2023.12.6 

### Panel Model

NSPanel EU Model

### What is the bug?

Compiling not possible

### Steps to Reproduce

I want to create a flash file for my sonoff NS display.
I used the following input data.

I tried it at leased 40 times with different conditions:

1. restart (real restart) Raspi
2. Delete
3. Add Limit the amount of resources used for compiling
4. restart ESP
5. Close Studio Code Server
6. etc.

I dont have any more ideas :-(

Please help me! Thanks

### Your panel's YAML

```yaml
INFO ESPHome 2023.12.6
INFO Reading configuration /config/esphome/dgzi3bildschirm.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/6051/head
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing dgzi3bildschirm (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/dgzi3bildschirm/src/main.o
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program as
compilation terminated.
*** [.pioenvs/dgzi3bildschirm/src/main.o] Error 1
========================= [FAILED] Took 183.90 seconds =========================
```
```


### ESPHome logs

```logs
> substitutions:
> 
> ###### CHANGE ME START ######
> 
>   device_name: "dgzi3bildschirm" 
>   wifi_ssid: "MY SSID"
>   wifi_password: "Password"
> 
>   nextion_update_url: "http://192.168.178.125:8123/local/nspanel_eu.tft" # URL to local tft File
> #  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
> 
> ##### CHANGE ME END #####
> 
> # Limit the amount of resources used for compiling
> esphome:
>   compile_process_limit: 1
> 
> ##### DO NOT CHANGE ANYTHING! #####
> 
> packages:
>   ##### download esphome code from Github
>   remote_package:
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
>     ref: main
>     files: [nspanel_esphome.yaml]
>     refresh: 1s
> 
> esp32:
>   framework:
>     type: esp-idf
> 
> ##### DO NOT CHANGE ANYTHING! #####
```
```


### Home Assistant logs

_No response_

**Comment by andythomas** [comment] 2024-01-16 15:45
Did you try 'Compile Using Your Computer' of [this guide](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1636).

**Comment by edwardtfn** [comment] 2024-01-16 16:08
And maybe trying stopping all other add-ons, not only Studio Code Server.

**Comment by Uli1900** [comment] 2024-01-16 16:11
ok, I will try. Thanks.

**Comment by Uli1900** [comment] 2024-01-16 16:26
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/98254065/54f81a60-d4d8-41e3-9ee7-8cbc33a2668f)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/98254065/b560970c-52c1-4e5b-96e0-25f99836851a)
seems to be a RAM Problem?

**Comment by edwardtfn** [comment] 2024-01-16 16:55
As per @andythomas suggestion, compiling in your computer might be a way.

**Comment by MichaelHeimann** [comment] 2024-01-18 10:06
I've also switched to compiling on my pc. HA with 2GB RAM cannot compile this (anymore?).
There's a compile_process_limit related line in the guide but maybe a RAM hint would be helpful, In my case 3GB were enough.

**Comment by Fredzxda** [comment] 2024-01-20 14:09
Same here. I can confirm it is no more possible to compile with only 2 GB. RAM usage increase to 2.3 GB after ugrading RAM to 3 GB on my VM.

**Comment by edwardtfn** [comment] 2024-01-20 16:30
Unfortunately I'm not aware of any way to handle this with limited memory. There are lots of messages related to this crash due to lack of memory while compiling, it's not only related to our project. Very small projects may work, but it it is a bit more complex, 2Gb is too few and the compiler will most likely crash.
The recommendation from ESPHome people is always to use the local computer to compile. 😞 

We are discussing about a pre built version, but unfortunately that still a bit far and also will limit customizations: #1583

**Comment by andythomas** [comment] 2024-01-20 16:58
I wanted to figure the memory limit via a VM, but @Fredzxda has already done that. I had an idea about increasing the swap to see, whether this handles the crash and will lead at least to a slow but successful compilation. Since you are already there half way, @Fredzxda would you be willing to try that? Or did anyone try?

**Comment by andythomas** [comment] 2024-01-24 09:57
I can confirm @Fredzxda findings and did a little bit more ground work. I always utilized a VM running Lubuntu LTS 22.04 for a small memory footprint. However, I used a graphical interface and not command line only. 

1. 3GB RAM and 500MB swap: 15 mins
2. 2GB RAM and 500MB swap: 20mins
3. 1GB RAM and 1GB swap: `==== [FAILED] Took 12004.43 seconds ====` :D
4. 1.5GB RAM and 1GB swap: 50min (borderline unbearable if you ask me)

I updated `install.md` accordingly and made a pull request #1720 @edwardtfn I will try to not make a mess out of my commit next time...

> [!NOTE]
> 4GB of memory are recommended if you are installing ESPHome as a Home Assistant add-on. 
Therefore, a RasPi 4 with 4GB RAM is the minimum if you are using a Raspberry Pi. 
A manual installation requires at least 2GB of memory and 500MB of swap space or 3GB of memory. 
With less memory the compiler will crash!

I suggest to close this issue. The OP has 2GB of memory which simply will not work. I am sorry for that @Uli1900 maybe you can utilize another computer for compiling.

**Comment by Uli1900** [comment] 2024-01-24 10:32
I solved the problem:

I replaced my Raspberry Pi 2GB with an Raspberry Pi with 8GB RAM and
I also used the hardware change to replace my SD Card with an 250 GB SSD storage.

Now it worked very well an in addition I am prepared for future.

**### Thanks for the community for help me in this case.**

**Closed** 2024-01-24 12:00 UTC
Labels: Bug, Validation pending
