### ISSUE TITLE
Alarm Unable to arm.

### ISSUE THREAD

**Issue by aman-sandhu** [Blackymas/NSPanel_HA_Blueprint#1193] opened 2023-10-20 18:35 UTC
Hi everything else is working great. Thank you for creating this.  When I try to arm the alarm and press Away. It says Unable to arm. You  entered  the wrong arm code. I am able to arm/disarm from my dashboard alarm panel with entering my code. Any help would be much appreciated.

Latest version 4.0.2

**Comment by edwardtfn** [comment] 2023-10-20 19:54
> It says Unable to arm. You entered the wrong arm code.

Where are you seeing this message?

**Comment by aman-sandhu** [comment] 2023-10-20 20:13
![notification](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59781323/de4438f9-f9ed-478f-8a85-3cdbb61b57aa)

<html>
<body>


serial_number: 242A0F
 model: PowerMaster-33E
 ready: true 
connected: true
 session_token: XXXXXXXXXXXXXXXXXXXXX
last_update: 2023-10-20T21:09:31.705978 
code_format: Number 
changed_by: XXXX
changed_timestamp: 2023-10-20 18:28:41 
alarm: false 
icon: mdi:shield-check
 friendly_name: Visonic Alarm
 supported_features: 3
--



</body>


Thank you for your swift response. 
Could it be the code_format: number????? 
</html>

**Comment by edwardtfn** [comment] 2023-10-20 20:17
> Could it be the code_format: number?????

Number shouldn't be an issue.
I believe the problem is related to the attribute `code_arm_required` missing in this entity.
When you change it using Home Assistant, a pin code is required?
What about when changing from the panel? Are you getting the keyboard to enter the pin code?

**Comment by aman-sandhu** [comment] 2023-10-20 20:23
![Alarm](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/59781323/08f57ef7-49f6-49b8-bfbf-53179a5a66df)

This is on my dashboard. I enter the code number and then select the required option.

**Comment by aman-sandhu** [comment] 2023-10-20 20:28
its a visonic alarm and I am using a custom integration. https://github.com/And3rsL/VisonicAlarm-for-Hassio
Its been working flawlessly and have setup node red flows and stuff for armed and disarmed states.

**Comment by edwardtfn** [comment] 2023-10-20 20:34
Ok. I will have to work on the code to show the keypad even when code is not required, but code format is provided.
I will take a look at this during this weekend.

**Comment by edwardtfn** [comment] 2023-11-06 19:39
I believe this issue is already resolved on `dev`, so I will close this and we reopen if needed.

**Closed by edwardtfn** 2023-11-06 19:39 UTC
Labels: bug, roadmap
